### ISSUE TITLE
backport storage

### ISSUE THREAD

**Issue by ilvalle** [web2py/pydal#115]
I'd discuss how storage can be backported in pydal
The main reason is to use it as a super class for Row

**Comment by mdipierro** [comment]
I remember playing a lot of Row and Storage until convergence. I am very reluctant to change them. Anyway, if you can make the case for tha change...

**Comment by gi0baro** [comment]
What benefits you think we achieve with that?

**Comment by ilvalle** [comment]
the benefit is speed. On my laptop with PG 9.1, the following
```
for row in db(db.table.id>0).select(limitby=(0, 1000000)):
    rtn = row.value
```
Took ~52s with master, ~33s using Row implemented as Storage.
This version passed all tests but one assertion https://github.com/web2py/pydal/blob/master/tests/sql.py#L727

The code is here: https://github.com/ilvalle/pydal/tree/storage

**Comment by v3ss0n** [comment]
Interesting results there. 
I for one , think storage is needed in pyDAL when using outside of web2py for convenience .

**Comment by ilvalle** [comment]
I've updated the branch with a fix for the failing assertion. Now it passes all tests in master and the ones in https://github.com/web2py/pydal/pull/139. Test code and initial results:
```
for row in db(db.table.id>0).select(limitby=(0, 1000000)):
    rtn = row.value
    rtn = row['value']
```
 | select | iterselect
-------- | -------- | --------
Row(object)|~53s / 1640MB |~46s / 24MB
Row(storage)|~36s / 1550MB | ~29s / 23.6MB

**Comment by gi0baro** [comment]
Seems pretty awesome.
Maybe we should move storage.py under *helpers* or *contrib* folder?

**Comment by ilvalle** [comment]
Contrib folder is for external stuff, namely maintained by someone else. I'll move it in helper.
Beside performance, using Storage reduces code repetition for common stuff (I haven't tried yet but DAL could inherit from Storage as well)

**Comment by gi0baro** [comment]
@ilvalle seems legit. Maybe you can put the `Storage` class in helpers/classes.py

**Comment by ilvalle** [comment]
I found an issue with the current ```Row(Storage)``` implementation 
```
>>> from pydal.objects import Row
>>> r=Row()
>>> hasattr(r, 'a')
True
```
which is not correct, I've added a couple of tests to highlight this situation and updated the code to fix it.
Storage is now called BasicStorage (to distinguish it from the original one). Before creating a PR, I ask someone to double check the code (mainly the pickle part)
