### ISSUE TITLE
Allow work with encoding different to utf 8

### ISSUE THREAD

**Issue by josejachuf** [web2py/pydal#126]
I have an application that uses a SQLServer database, which is part of another system. The database is latin1

when I create the DAL object I pass the parameter db_codec = 'latin1'

This solves the conversion to utf8 when I read data, but when I write it does in utf8.

I solved it by doing the following: If I create a new record from a SQLFORM use "dbio = False", then analyze and convert the dictionary form to latin1:

for k in form.vars:
         if isinstance (form.vars [k], unicode) or isinstance (form.vars [k], str):
             form.vars [k] = form.vars [k] .decode ('utf8'). encode ('latin1')

db.mytable.insert (*\* dict (form.vars))

Then, for a very simple task you have to write a lot of code.

The proposal is to become the edges to encoding necessary:

Database <---enconding1 (default utf8)---> DAL (utf8) <---encoding2 (default utf8)---> Application

**Comment by timnyborg** [comment]
Seconded.

I think this would be a solution to the problem I'm having:
https://groups.google.com/forum/#!topic/web2py/awysZeeXk28
