### ISSUE TITLE
Replace project description

### ISSUE THREAD

**Issue by kirsn** [web2py/pydal#13]
Replace the current description: *the web2py abstraction layer without web2py*
with the more descriptive: *This is the web2py's Database Abstraction Layer. It does not require web2py and can be used with any Python program.*

**Comment by gi0baro** [comment]
@mdipierro can you do this?

**Comment by mdipierro** [comment]
yes. Later today or tomorrow.

**Comment by gi0baro** [comment]
@mdipierro still waiting for this ^^

**Comment by mdipierro** [comment]
done. And I made you co-owner
