### ISSUE TITLE
DAL runtime debug=True

### ISSUE THREAD

**Issue by angeloc** [web2py/pydal#132]
Hi All,

I tried t set debug=True in dal at runtime, it doesn't seem to work. I think could be really usefull to have a switchable debugging in DAL, foremost in that occasion in which you can't understand if it's your code or your data buggy.

Thank you for your time!

**Comment by gi0baro** [comment]
@angeloc Hi angelo, I inspected this a bit, and actually with pydal behind weppy the debug mode is working. I suppose is a logger problem. Are you using pydal behind web2py or directly with console?

@mdipierro I think we can add a `logging.StreamHandler(sys.stdout)` to pyDAL as default and patch web2py to inject its own loggers. So if pydal is used directly via console will log debug informations. What do you think?

**Comment by angeloc** [comment]
Poking at the coe I found the way some time ago.
Enable the logging is simply a matter of:
db._debug =True
When you want to disable:
db._debug = False.

It's really useful for me, the only drawback I found is that sometimes
web2py crashes cause this logging is not threadsafe.

Sincerely, Angelo.
