### ISSUE TITLE
record representation gone...

### ISSUE THREAD

**Issue by niphlod** [web2py/pydal#135]
following this thread https://groups.google.com/forum/#!topic/web2py/2i9zfAzG2s8
```
db.define_table('person',
                    Field('name'),
                    format='%(name)s')
db.define_table('thing',
                    Field('name'),
                    Field('owner_id', 'reference person'),
                    format='%(name)s')
```
there's no 'represent' function attached to db.thing.owner_id, so serializers (such as SQLTABLE) can't fetch the correct representation.... where did it go ?

**Comment by gi0baro** [comment]
Probably there's something wrong with the auto_format method I've introduced in helpers/methods.py.. Will investigate this tomorrow.

**Comment by niphlod** [comment]
k. once fixed, tag the version, @mdipierro would probably need to release another quickfix 2.10.4 . 
BTW: we really should include this in the automated test suite...

**Comment by gi0baro** [comment]
@niphlod the PR #137 should fix the issue.
Regarding the release of a new version, since we're still working on a lot of new stuffs for 15.04, I think I can create a new branch named "15.03-maintenance" and cherry-pick the fixes we need for web2py 2.10.4
what do you think?

**Comment by ilvalle** [comment]
I agree with you, current pydal is not ready for being part of web2py
2.10.4.
Lets create a new branch '15.03-maintenance' based on 15.03 and apply #137
<https://github.com/web2py/pydal/pull/137> to both master and 15.03-
maintenance


 Paolo

2015-04-14 10:50 GMT+02:00 Giovanni Barillari <notifications@github.com>:

**Comment by niphlod** [comment]
messy but seems the only possibile solution for a "quickfix release".

**Comment by niphlod** [comment]
@gi0baro : can you look into it ? https://groups.google.com/d/msg/web2py-developers/9I2uBKH90bM/MXoraob-r9IJ
