### ISSUE TITLE
Rows.as_json failing with default JSON

### ISSUE THREAD

**Issue by nursix** [web2py/pydal#141]
Rows.as_json fails with default JSON (Python 2.7) because it doesn't convert datetimes into strings. 

There is currently no option to tell Rows.as_json() to convert datetimes into strings like:

    jsonstr = row.as_json(datetime_to_str=True)

...and it defaults to False:

    def as_dict(self, datetime_to_str=False, custom_types=None):

That won't work with standard json.dumps.

However, even if that would be overridable: datetime_to_str is not propagated through the recursion in Row.as_dict when v is a Row (e.g. as result of a join):

            elif isinstance(v,Row):
                d[k]=v.as_dict()

Shoud be:

            elif isinstance(v,Row):
                d[k]=v.as_dict(datetime_to_str=datetime_to_str,
                               custom_types=custom_types,
                               )

So, with standard json.dumps as serializer, Rows.as_json does currently not work.

**Comment by nursix** [comment]
Related to this commit, btw:

https://github.com/web2py/pydal/commit/788df0e05fa9c8a292c5ba399eb5a8e6b21de1a3#diff-68220c912f02a03fd8bce58415479334L2742

The datetime_to_str logic should probably be retained here (plus the above fix) to make it work with default json.dumps again?

Or is there another way?

**Comment by gi0baro** [comment]
Hi nursix, this is my test on current master:

```python
>>> from pydal import DAL, Field
>>> db = DAL()
>>> db.define_table('test', Field('a'), Field('date', 'datetime'))
<Table test (id,a,date)>
>>> from datetime import datetime
>>> db.test.insert(a='asd', date=datetime.utcnow())
1L
>>> rows = db(db.test.id > 0).select()
>>> rows.as_json()
u'[{"a": "asd", "date": "2015-04-20 14:10:07", "id": 1}]'
>>> rows[0].as_json()
u'{"a": "asd", "date": "2015-04-20 14:10:07", "id": 1}'
```

The current serialization in pyDAL actually converts date, time and datetime objects to strings in order to give valid JSON output.

Am I missing something?

**Comment by nursix** [comment]
I think the problem is that the latest pyDAL version (using serializers.json for Rows.as_json) isn't in web2py yet.

I repeated your test with the current web2py version and get this:

```>>> from pydal import DAL, Field
>>> from datetime import datetime
>>> db.define_table('test', Field('a'), Field('date', 'datetime'))
<Table test (id,a,date)>
>>> from datetime import datetime
>>> db.test.insert(a='asd', date=datetime.utcnow())
2L
>>> rows = db(db.test.id > 0).select()
>>> rows.as_json()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/objects.py", line 2717, in as_json
    return json.dumps(items)
  File "/usr/lib64/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2015, 4, 20, 15, 2, 39) is not JSON serializable
>>> rows[0].as_json()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/dominic/work/web2py/gluon/packages/dal/pydal/objects.py", line 213, in as_json
    return json.dumps(item)
  File "/usr/lib64/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2015, 4, 20, 15, 2, 39) is not JSON serializable
>>> ```

Would your test also work with the result of a join (i.e. datetime in a nested Row?).

In any case - if it works with the latest PyDAL, then it would be good to update web2py so that users benefit from the fix.

Many thanks.

**Comment by gi0baro** [comment]
@nursix yes, It's already merged on master as you can see from https://github.com/web2py/web2py/pull/923

Will be released in 2.10.4 in the next days.

**Comment by nursix** [comment]
Weird - I'm using web2py trunk, and don't see this version there...

**Comment by gi0baro** [comment]
@nursix you're right. Let me check with the other developers.

**Comment by nursix** [comment]
No urgency - I've patched my local pyDAL, and blacklisted the current web2py trunk version for deployments with our system. That's btw the actual reason why I'm routinely testing our system (=Sahana Eden) against web2py trunk: detecting regression problems.

Just trying to make sure that it either gets fixed upstream, or we have a workaround for it in place.
Sorry for bothering you.

**Comment by gi0baro** [comment]
@nursix no problem. web2py trunk now is patched: https://github.com/web2py/web2py/pull/930

**Comment by nursix** [comment]
Excellent, many thanks.
