### ISSUE TITLE
with_alias()

### ISSUE THREAD

**Issue by niphlod** [web2py/pydal#143]
https://github.com/web2py/web2py/issues/932

**Comment by gi0baro** [comment]
Do we have a traceback for this?

Maybe can be related to serializations problems and maybe is fixed in master (he is using web2py 2.10.3)..

**Comment by niphlod** [comment]
I don't have it. I merely copy around tickets since as long as they don't appear here they're not considered. :P

**Comment by gi0baro** [comment]
So.. maybe we can try to reproduce it on pydal *15.03-maintenance*?

**Comment by niphlod** [comment]
I'd say the usual: test with 15.03, add a regression test so it won't happen again, test on master, eventually fix both 15.03 and master, close the ticket. reiterate.

**Comment by ilvalle** [comment]
https://github.com/web2py/pydal/pull/148 fixed this issue.

**Comment by gi0baro** [comment]
I think #148 is not merge–able onto *15.03-maintenance*, I would like to consider this closed since the master is patched and it will be available to users in the next release. @niphlod what do you think?

**Comment by niphlod** [comment]
I think that we needed to ship 2.10.4 "fast" but we missed the occasion, and the bug of representers seems to have resurfaced. At this point let's close this and web2py/web2py#932 (if we're positive that next release won't have it) and cross our fingers for a 2.10.5 completely bug-free.
