### ISSUE TITLE
Row["table.field"] not working with LazySets

### ISSUE THREAD

**Issue by nursix** [web2py/pydal#173]
File ".../web2py/gluon/packages/dal/pydal/objects.py", line 60, in __getitem__
    return e[m.group(2)]
TypeError: 'LazySet' object has no attribute '__getitem__'

**Comment by ilvalle** [comment]
Hi, can you provide a simple spinet of code to reproduce the error?
Try to add ```TypeError``` in the except at line 61.

**Comment by nursix** [comment]
Difficult to pull this together ;) since I'm using PyDAL not developing it.

I'm selecting a row from the table "org_organisation":

    >>> row = db(table.id>0).select(table.id, table.name, limitby=(0, 1)).first()
    >>> row
    <Row {'id': 1L, 'name': 'International Committee of the Red Cross'}>

I can easily access the "id" field as attribute:

    >>> row.id
    1L

But it breaks when I try to use the Field or the field name as index:

    >>> row["org_organisation.id"]
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/home/dominic/work/web2py/gluon/packages/dal/pydal/objects.py", line 60, in __getitem__
      return e[m.group(2)]
      TypeError: 'LazySet' object has no attribute '__getitem__'
    >>>

**Comment by nursix** [comment]
Catching TypeError (in addition to KeyError) does indeed help - but it looks wrong to me.

The "return e[m.group(2)]" should probably be in a separate try/except?

**Comment by niphlod** [comment]
uhm. 
row['table']['field'] is supposed to work. 
not sure if row['table.field'] has ever been supported....

**Comment by nursix** [comment]
Yes, it was always supported.

You could always use the Field as index - which is why there is this regex for the dot-notation.

**Comment by ilvalle** [comment]
row['table.field'] works, I've also added tests for it. https://github.com/web2py/pydal/blob/cda69216d45b3be312f7a91f48db6837801357dc/tests/sql.py#L1823
@nursix, catching ```TypeError``` fixed the issue?

**Comment by nursix** [comment]
It did fix the problem, yes - it just looked wrong to me to catch two unrelated exception with the same except. But if you say that's ok - it's your coding conventions ;)

**Comment by ilvalle** [comment]
ok, I'll create a PR to fix it. LazySet isn't a dict, so doing LazySet[...] raise a typeError.
However, I'm still not able to reproduce issue. I'd add a test along with the fix.

**Comment by nursix** [comment]
Many thanks.

**Comment by mdipierro** [comment]
Yes. This is supposed to work

**Comment by ilvalle** [comment]
the following is the easiest example that shows this issue:
```
db=DAL(url)
db.define_table('tt',  Field('tt_id', 'reference tt'))
row = db(db.tt).select().first()
row.id
row["tt.id"]
```
