### ISSUE TITLE
Update mysql adapter `lastrowid()`

### ISSUE THREAD

**Issue by gi0baro** [web2py/pydal#178]
As pointed out @niphlod on https://github.com/web2py/web2py/issues/667, we can use the better `cursor.lastrowid`.

For more infos: https://www.python.org/dev/peps/pep-0249/#lastrowid

**Comment by gi0baro** [comment]
Note: this is only a *stylistic* choice, the resulting behavior should be the same.

**Comment by ilvalle** [comment]
I agree on using ```lastrowid``` but double check that works on all major
drivers. My experience is that not all static attributes are available on
all drivers. For example ```rowcount``` doesn't work on all drivers.

 Paolo

2015-05-05 1:14 GMT+02:00 Giovanni Barillari <notifications@github.com>:
