### ISSUE TITLE
notnull & unique for reference fields

### ISSUE THREAD

**Issue by ilvalle** [web2py/pydal#181]
Related discussion and issue https://groups.google.com/d/topic/web2py-developers/o3np10fWKzM/discussion
https://github.com/web2py/web2py/issues/653

We should update https://github.com/web2py/pydal/blob/master/pydal/adapters/base.py#L372 and double check on all major backends that everything works. Some tests are needed.

**Comment by gi0baro** [comment]
@ilvalle any status update on this? Is this https://github.com/ilvalle/pydal/commit/f5eb12eb8b0b26f8ba5e59fd5fe5580d7ffed091 ready?
