### ISSUE TITLE
Inserting Unicode on MSSQL

### ISSUE THREAD

**Issue by timnyborg** [web2py/pydal#189]
I've been hammering my head against Unicode, the only remaining problem with our particular web2py implementation.  Non-latin characters just get garbled.  And I think I've found the cause.

pypyodbc seems to handle unicode properly only if it's used in a parameterized way:
This pypyodbc command works:

            cur.execute(u'''UPDATE student SET surname=? WHERE student.id = 1''', (u'江文',))

While any attempt to put the hanzi in the string results in garbage on the database:

            cur.execute(u'''UPDATE student SET surname=N'江文' WHERE student.id = 1''')
            cur.execute(u'''UPDATE student SET surname='江文' WHERE student.id = 1''')
            cur.execute('''UPDATE student SET surname=N'江文' WHERE student.id = 1''')
            cur.execute('''UPDATE student SET surname='江文' WHERE student.id = 1''')

Web2py's calls to the adapter's execute function are not parameterized, and so the encoding is lost:

Base.py, def update(), line 979

            self.execute(sql)

But running the following succeeds:

            self.execute(u'''UPDATE student SET surname=? WHERE (student.id = 1)''', (u'江文',))

I imagine parameterization is not going to happen, given web2py's query string building, so any ideas?

**Comment by niphlod** [comment]
we're revamping unicode treatment for mssql in a short time. Be prepared to do a bit of testing :-P

**Comment by timnyborg** [comment]
Count me pleased as punch!  I'll do my bit.

**Comment by niphlod** [comment]
@timnyborg : please see current trunk... test mssql3n and mssql4n adapters

**Comment by niphlod** [comment]
@timnyborg : news ?

**Comment by timnyborg** [comment]
Using either of them (but normally mssql3n, as the DB is 2005):

Having no problems with the ILIKE + LOWER, so that fix seems to be working.
However, while extended-ASCII works fine, Unicode-only alphabets break conversion (French vs Polish): 

Façade > Façade
Gdańsk > GdaDsk

In some odd cases, the conversion breaks entirely, and an Internal Server Error results:
RaúlGdańsk > error
Raúl Gdańsk > Raúl GdaDsk

**Comment by timnyborg** [comment]
I've been playing around with the def update(), and stumbled upon a method that seems functional (though I'm an absolute novice with the DAL source):

Namely, I've replaced  def _update() with a parameterized version, then converted all strings in the update to unicode objects.  With that, updating a string to '江文' works

    def _update_param(self, tablename, query, fields):
        if query:
            #if use_common_filters(query):
            #    query = self.common_filter(query, [tablename])
            sql_w = ' WHERE ' + self.expand(query)
        else:
            sql_w = ''
        sql_v = ','.join(['%s=%s' % (field.sqlsafe_name, '?') \
                              for (field, value) in fields])
        tablename = self.db[tablename].sqlsafe
        return 'UPDATE %s SET %s%s;' % (tablename, sql_v, sql_w)        
        
    def update(self, tablename, query, fields):
        #sql = self._update(tablename, query, fields)
        sql = self._update_param(tablename, query, fields)
        
        try:
            field_vals = [value.decode('utf8') if isinstance(value, str) else value for (field, value) in fields]
                 
            #self.execute(sql)
            self.execute(sql, field_vals)

        except Exception:
            e = sys.exc_info()[1]
            table = self.db[tablename]
            if hasattr(table,'_on_update_error'):
                return table._on_update_error(table,query,fields,e)
            raise e
        try:
            return self.cursor.rowcount
        except:
            return None

**Comment by timnyborg** [comment]
Ack.  I've done a quick test installing web2py on a local windows machine, and mssql3n is working _perfectly_.  While the tests above are on on Debian machine with pyodbc & FreeTDS, on the Windows machine, inserts, updates, and selects against the same database as above are all working with unicode characters in everything I test.

So it may be a problem inserting pyodbc, or with my configurations.

**Comment by mdipierro** [comment]
Do you think we can close this?

**Comment by niphlod** [comment]
on windows it seems that all is playing nicely. Didn't have time to play with the zillion configs of freeTDS ... maybe @timnyborg had better luck.

**Comment by gi0baro** [comment]
I'm gonna close this. @timnyborg feel free to re-open this if you will encounter any additional issue.
