### ISSUE TITLE
Inconsistency between Row.get(key) and Row[key]

### ISSUE THREAD

**Issue by nursix** [web2py/pydal#197]
There is a (recently introduced) inconsistency between Row.get(key) and Row[key]

Where the Row is the result of a join, you can access fields in the sub-Rows like Row["tablename.fieldname"] - but not like Row.get("tablename.fieldname").

In earlier versions, the behavior of Row[key] and Row.get(key) was the same - changing the behavior of Row.get(key) breaks large parts of our code (not backwards-compatible), and it also seems very inconsistent and counter-intuitive compared with both normal Python dicts as well as gluon.storage.Storage.

**Comment by nursix** [comment]
Yeah - and with itself of course. Because where the Row is not the result of a join, you can access fields both as Row["fieldname"] and Row.get("fieldname"). 

But not if you have multiple sub-Rows, then the two methods behave differently. Row["tablename.fieldname"] works, but Row.get("tablename.fieldname") does not.

**Comment by gi0baro** [comment]
@ilvalle can you look at this?

**Comment by ilvalle** [comment]
I'll look at this later today

 Paolo

2015-05-25 9:12 GMT+02:00 Giovanni Barillari <notifications@github.com>:
