### ISSUE TITLE
escaping correctly "LIKE" for not-so-funny ANSI T-SQL patterns

### ISSUE THREAD

**Issue by niphlod** [web2py/pydal#212]
I know, I was an adamant advocate of leaving LIKE as it behaves in the backend. 
The thing is, LIKE is used for contains(), startswith(), endswith(), etc. 
I think newbies expect to search (at least) for '_', '%' correctly. Fortunately, we have `LIKE foo ESCAPE '\'`

I was working on a quickfix but got shortcircuited for the better part of 2 hours (or more? I can't tell right now :D )
Tests to try ....
- `contains('%')` matches 'abc%def' but not 'whatever' (`%` in T-SQL is **0 or more anything**)
- `contains('a%c')` matches 'ya%cy' but not 'yabxcy' (`%` in T-SQL is **0 or more anything**)
- `contains('_')` matches 'abc_def' but not 'whatever' ( ``_`` in T-SQL is **exactly one anything**)
- `contains('a_c')` matches 'ya_cy' but not 'yaxcy' ( `_` in T-SQL is **exactly one anything**)
- `startswith('_')` matches '_abcdef' but not 'xabcdef'
- `startswith('%')` ....
etc. etc etc . 

Think being able to search for a string like "30% discount" or "%%weird" or "_private" . happens.

In addition to that, mssql is a taddle bit less cooperative with those kind of things. 
It treats `LIKE '[whatever]'` as a class of characters (regex-like, albeit limited), so `[` and `]` needs escaping too. Plus a few niceties like 

    If there is no character after an escape character in the LIKE pattern, the
    pattern is not valid and the LIKE returns FALSE. If the character after an
    escape character is not a wildcard character, the escape character is
    discarded and the character following the escape is treated as a regular
    character in the pattern. This includes the percent sign (%), underscore (_),
    and left bracket ([) wildcard characters when they are enclosed in double
    brackets ([ ]). Also, within the double bracket characters ([ ]), escape
    characters can be used and the caret (^), hyphen (-), and right bracket (])
    can be escaped.

I don't know if I'll ever be able to fix it for the 100% of cases.

**Comment by niphlod** [comment]
BTW: we can also go for documenting the notable exceptions (i.e. startswith('foo') is just a shortcut for like('%' + foo) and follows the same exceptions as like())....the problem is with the CONTAINS() that is documented to behave perfectly for list:string and such.

**Comment by niphlod** [comment]
posted the fix for any case I could come up with in mssql. every other adapter **should** need a similar fix.
BTW: if this gets merged, changelog needs a mention of the "escaping". And, albeit less important, MSSQL gained basic regexp() capabilities, too.

**Comment by niphlod** [comment]
all in favour ? I'm thinking to refactor the patch a bit and:
- leave like() as it is (treated on the underlying backend without massaging, passed as it is to `LIKE`)
- add an "escape_with" parameter to the like() to enable using a correct escaping (should the user need to, it'll turn to `LIKE 'foo' ESCAPE 'b'`)
- handle startswith(), contains(), endswith() with automatic massaging/escaping before passing to the raw `LIKE` statement


@mdipierro , @abastardi , @ilvalle , @gi0baro : thoughts ?

**Comment by gi0baro** [comment]
@niphlod I'm ok with that

**Comment by mdipierro** [comment]
Can this be closed?

**Comment by niphlod** [comment]
after the commit with the pretty long comment (https://github.com/web2py/pydal/commit/221146064e47bc5dcb993a1e289fc06eb7589c64) I'd say yes. Remains to be seen if noSQL will eventually catch up with the intricacies.
As of right now everything should be under tests for the previously-failing corner-cases.
