### ISSUE TITLE
validate_and_insert() not returning record id

### ISSUE THREAD

**Issue by franciscocosta** [web2py/pydal#215]
When I validate and insert using `ret = db.mytable.validate_and_insert(field='value')` using valid data ret returns:

    <Row {'errors': {}, 'id': None}>

the record is corrected inserted but the id is not returned

**Comment by ilvalle** [comment]
Which backend are you using?

 Paolo

2015-06-11 18:01 GMT+02:00 Francisco Costa <notifications@github.com>:

**Comment by franciscocosta** [comment]
I'm using web2py 2.11.2

**Comment by ilvalle** [comment]
Which db adapter? Is a ```db.table.insert(...)``` returning the id?

**Comment by franciscocosta** [comment]
MongoDB adapter.. 
`db.table.insert(...)` returns `None`

**Comment by stephenrauch** [comment]
I was unable to duplicate this. Can you share some details of table structure and inserted values?

**Comment by ilvalle** [comment]
Me neither.
With mongodb insert returns None only when the operation has been sent to
mongodb but there is no guarantee that has been safety written to the fs.
Have you changed the safe parameter?

Replacing
```w=self.safe```
with
```fsync=bool(self.safe)```
in pydal/adapters/mongo.py:96 should fix the issue.

 Paolo

2015-06-11 21:24 GMT+02:00 Stephen Rauch <notifications@github.com>:

**Comment by franciscocosta** [comment]
Try this code:

    db = DAL(
        'mongodb://localhost/%s' % request.application,
        adapter_args={'safe': False},
        pool_size=10
    )

    db.define_table(
        'users',
        Field('id', required=True, unique=True, writable=False, readable=False),
        Field('name', 'string', required=False),
    )

    user = {}
    user['name'] = 'John'
    ok = db.users.insert(**user)
    print ok


it lloks like if I change `adapter_args={'safe': True}` and remove the `pool_size=10` it works as expected

**Comment by ilvalle** [comment]
Yes, you should use safe=True to get an id (this is the default behavior of the adapter) .

**Comment by franciscocosta** [comment]
Thanks Paolo

**Comment by franciscocosta** [comment]
but if I have `pool_size` bigger than 0 it also returns `None` on insert

**Comment by stephenrauch** [comment]
When I run your test code with safe=True and pool_size=10, the insert returned an object ID

**Comment by mdipierro** [comment]
I think this can be closed.
