### ISSUE TITLE
adapter.reconnect() issues with MongoDBAdapter

### ISSUE THREAD

**Issue by gi0baro** [web2py/pydal#222]
Without connection pools I'm getting this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyDAL-15.05.29-py2.7.egg/pydal/connection.py", line 106, in reconnect
    self.cursor = cursor and self.connection.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
```
Confirmed with current master.

**Comment by gi0baro** [comment]
Basically the `connector` function provided by `MongoDBAdapter` is returning `None`. pymongo v3.0.2

**Comment by gi0baro** [comment]
Actually I'm getting errors also with pools:
```
File "/usr/local/lib/python2.7/dist-packages/pyDAL-15.05.29-py2.7.egg/pydal/connection.py", line 117, in reconnect
    self.cursor = cursor and self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 2066, in __call__
     self.__name)
TypeError: 'Collection' object is not callable. If you meant to call the 'cursor' method on a 'Database' object it is failing because no such method exists.
```

**Comment by gi0baro** [comment]
@ilvalle any ideas about this?

**Comment by stephenrauch** [comment]
You can assign this to me if you like.  I am trying to duplicate, but I think I found the problem and am pursuing it now.

What test case or scenario is causing this?

**Comment by gi0baro** [comment]
@stephenrauch thank you. Actually is simply the standard flow of weppy handlers https://github.com/gi0baro/weppy/blob/master/weppy/dal/base.py#L11: reconnecting on incoming request, disconnecting on built response. I'm quite surprised is not happening in web2py as well, since the flow is the same.

**Comment by stephenrauch** [comment]
@gi0baro the bottom line problem (why it worked in web2py, but not weppy) is that weppy was calling self.db._adapter.reconnect() without parameter 'cursor=False'.  The PR (https://github.com/web2py/pydal/issues/226) I just submitted adds some test cases from the SQl tests and removes the need for the parameter.

**Comment by mdipierro** [comment]
Can this be closed?
