### ISSUE TITLE
Row.__getattr__ raises AttributeError when trying to access '_extra'

### ISSUE THREAD

**Issue by gi0baro** [web2py/pydal#229]
Just spotted. I have this `Row` returned from pyDAL:

```python
<Row {'users': {'id': 26470719833643260735021266671L}, '_extra': {'registration_id': '', 'last_name': 'Barillari', 'first_name': 'Giovanni', 'reset_password_key': '', 'password': '***', 'registration_key': 'b40bde36-258a-48fb-b565-ec22cabc0586', 'email': '***'}}>
```

In v15.03 was working as expected. In current master the problem seems caused by the difference behavior between `Row.__getitem__` and `Row.__getattr__`.
@ilvalle maybe a consequence of your refactoring with `BasicStorage`?
I propose to add a:

```python
__getattr__ = __getitem__
```
in `Row` class.

**Comment by ilvalle** [comment]
Can you double check with https://github.com/web2py/pydal/tree/v15.05.29?

**Comment by gi0baro** [comment]
@ilvalle 15.05.* seems to be affected too.
Looks correlated to the fix you made for `get()`: https://github.com/web2py/pydal/commit/6480b27f7aa4cc3ba10c81758743219ce3cf92f4

**Comment by ilvalle** [comment]
I see, however it is strange that tests are still passing, probably they are not enough. 
You can add the fix proposed, I suggest adding a test for this issue too

**Comment by gi0baro** [comment]
@ilvalle maybe depends on how attributes are added as normal keys or under `_extra` attribute. I had never inspected the flow. Will push a PR later today.

**Comment by ilvalle** [comment]
Is it still valid? Can you provide a failing example?

**Comment by gi0baro** [comment]
I think `__getattr__` should behave as `__getitem__`.

**Comment by gi0baro** [comment]
Update: actually I've re-tested this with latest master. The issue will show up only if you try to access something inside `_extra` as attributes:
```python
>>> row['_extra']['asd']
'lol'
>>> row['asd']
'lol'
>>> row._extra.asd
'lol'
>>> row.asd
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/sellf/pydal/pydal/helpers/classes.py", line 348, in __getattr__
    raise AttributeError
AttributeError
```
Now, since in `_extra` you usually have keys like `'COUNT(contacts.id)'`, I don't know if there are conditions where `_extra` items are accessible as attributes.
@ilvalle @mdipierro should we consider this not reproducible and close it? Do you know any condition where `_extra` items have proper naming to be accessible as attributes?

**Comment by ilvalle** [comment]
I don't think is documented anywhere

 Paolo

2015-07-02 10:42 GMT+02:00 Giovanni Barillari <notifications@github.com>:

**Comment by gi0baro** [comment]
@mdipierro I'm gonna close this as invalid. Feel free to re-open if you think is a valid bug.

**Comment by gi0baro** [comment]
@ilvalle hints on how to solve this?

**Comment by mdipierro** [comment]
Although theory I agree that__getattr__ should behave as __getitem__, in practice they did not. This is because in 
    row.xxx
    row['yyy']
xxx is constraint to be alphanumeric and therefore has to be a field (and we can optimize for this) or a table (in result of joins) while yyy can be an expression (from _extra) or a 'table.field'. I do not object to having a single underlying implementation unless we make it slower by ignoring the fact that they they serve different purposes. Has anybody test the speed of the code after the change? Some time ago we spent huge amount of time refactoring this code since it is a web2py bottle neck.

**Comment by ilvalle** [comment]
According to my test, we have better performance now. 
Surely, placing ```__getattr__ = __getitem__ ``` in Row will have its impact. Before proposing the new implementation of Row I didn't know you could access an element of _extra _directly_.
As written in https://github.com/web2py/pydal/issues/246#issuecomment-118835089, my proposal is to change the current approach: writing ```db(db.tt).select('vv')``` should output  ```<Row {'vv': 1L}> ``` which is the output of  ```db(db.tt).select(db.tt.vv) ``` . Now we have  ```<Row {'_extra': {'vv': 1}}> ```. By doing that, we can avoid to add ```__getattr__ = __getitem__ ``` in Row.
I don't see why we should have two different results for the same select.

**Comment by mdipierro** [comment]
OK. As long as performance was tested I think the code is fine as it is now. Can we close this issue?

**Comment by gi0baro** [comment]
@mdipierro don't close this until we successfully decided how to manage this. #246 is a duplicated and a consequence of this.

**Comment by gi0baro** [comment]
@ilvalle should we wait for the change you proposed in #246 to release 15.07?

**Comment by ilvalle** [comment]
For me is ok, if it doesn't decrease the overall performance.

 Paolo

2015-07-08 22:00 GMT+02:00 Giovanni Barillari <notifications@github.com>:
