### ISSUE TITLE
Patch to fix bugs in FreeBSD

### ISSUE THREAD

**Issue by josejachuf** [web2py/pydal#239]
The problem reported here [1], which affects FreeBSD, apparently in version 10, is corrected by applying the following patch to 

file /web2py/gluon/packages/dal/pydal/contrib/portalocker.py

--- portalocker.py.old	2015-05-30 13:33:10.000000000 -0300
+++ portalocker.py	2015-06-25 15:46:24.000000000 -0300
@@ -119,7 +119,7 @@
             lock(self.file, LOCK_EX)
             if not 'a' in mode:
                 self.file.seek(0)
-                self.file.truncate()
+                self.file.truncate(0)
         else:
             raise RuntimeError("invalid LockedFile(...,mode)")

[1] https://groups.google.com/forum/#!topic/web2py/E-E1E1pdkYY

**Comment by mdipierro** [comment]
thanks. in trunk.

**Comment by mdipierro** [comment]
Done!
