### ISSUE TITLE
Key error when defining reference to table before table definition

### ISSUE THREAD

**Issue by evan54** [web2py/pydal#258]
This is a problem I found documented elsewhere but I experienced it when I upgraded to 2.11.2

The problem was mentioned here:

https://groups.google.com/forum/#!topic/web2py/58aG2cdzk8s

basically when you define a reference to a table with 'reference tablename' before you define the table. eg:

db.define_table( 'dogs' , Field( 'owner' , 'reference people' ) )
db.define_table( 'people' , Field( 'name' ) )

**Comment by gi0baro** [comment]
@evan54 What's the point of defining `people` table after? Just define it first.

**Comment by evan54** [comment]
I mean I've made my code work by switching the order. I thought I'd just report this as this doesn't seem to be expected behaviour. ie I thought that it is meant to work regardless of the order. If not I'll close the issue as a non issue.

**Comment by abastardi** [comment]
According to [this thread](https://groups.google.com/forum/#!msg/web2py-developers/cU_ZpBAOXAU/6Hx2OPxEDuIJ), the problem noted here breaks backward compatibility and should be fixed. According to that thread, it looks like it was fixed once before, though presumably it has broken again. This issue should be re-opened.

**Comment by gi0baro** [comment]
@abastardi I simply don't agree. I can't see any good reason to support a **wrong** behaviour that already caused discussions 4 years ago.

**Comment by abastardi** [comment]
@gi0baro, I don't have a particularly strong opinion either way, but the result of the discussion to which you refer was that this *should* be fixed, and the conclusion was that it actually *was* fixed (if so, then it must have subsequently broken again). I'll post on the developers list, and if everyone is OK with the current behavior, we can leave it.

Note, even if we conclude that allowing circular references is bad database design, there can still be a use case for allowing pydal reference fields to be created before or without their referenced tables being defined. Suppose for example we have:

    db.define_table('table_c',
        Field('table_a', 'reference a'),
        Field(table_b', 'reference b'),
        [other fields])

where `table_a` and `table_b` are large, complex tables. Now suppose there are some requests where we need the data from `table_c`, but we do not need any data from `table_a` or `table_b`. On such requests, we might want to forego the definitions of the latter two tables for improved efficiency. This is not an example of "wrong" behavior.

In any case, if we decide not to support definitions of fields that reference tables that are not defined, we might also consider preventing that behavior when `lazy=True`. Right now it is somewhat confusing that code that works with `lazy=True` suddenly fails when changing to `lazy=False`. At the very least, we should document this disparity.

**Comment by abastardi** [comment]
If it is complicated to fix, I would lean towards leaving the current behavior and maybe adding a note to the book indicating that using `lazy=True` is a strategy for when you need to define a reference field without the referenced table having been defined (whether for circular references or other purposes).

**Comment by BuhtigithuB** [comment]
I have such chicken and eggs issue like that : 

Where auth_user reference address table, address reference phone number but phone number reference auth_user...

I guess schema could be refined, but it appends sometimes that you need circular reference, just think to the fact that address is referenced by auth_user, it needs to be defined before auth_user, but if you use auth_signature you are going to referenc auth_user from every table, so if they are reference before the auth tables you are screwed...

**Comment by abastardi** [comment]
Note, this was also discussed [here](https://github.com/web2py/web2py/issues/699) and [here](https://groups.google.com/forum/#!topic/web2py-developers/ZnqC0GZiTd8/discussion).

One concern -- in the second link above, @niphlod noted that the old behavior only seemed to work but in fact never created the foreign key constraints in the database. I'm wondering if that is still true now when `lazy=True`. If so, that might be an argument for disabling this behavior even when `lazy=True` (unless of course we are going to fix it completely, possibly using something like https://github.com/ilvalle/pydal/tree/deferred-references).
