### ISSUE TITLE
Accent-insensitive LIKE

### ISSUE THREAD

**Issue by nursix** [web2py/pydal#263]
Hi all--
we have several use-cases where we need a LIKE query to ignore accents (e.g. matching "a" and "á"). Is this possible already, or can it be made possible?

PostgreSQL (which all of these cases use) provides the unaccent-extension, so that I thought it might be useful to expose that, either as unaccent() operator for Expressions, or as an extension to the .like() operator as in: Field.like(..., ignore_accents=True).

Surely, unaccent needs to be switched on by "CREATE EXTENSION unaccent", which could happen e.g. during adapter instantiation, parametrized as unaccent=True.

How complicated would that be? How can it be done? Anyone who can assist, or give the right pointers?

Many thanks,
Dominic

P.S. Alternative to use REGEX already considered, and actually working, but not scalable enough.

**Comment by nursix** [comment]
Please note that we're talking about a database with up to 500k records and at least 3-5 fields per record, so we're looking for a truly scalable solution here. Any post-query variants seem therefore out of the question.

**Comment by niphlod** [comment]
craft your own query, it's not that difficult. 
Asking for something that is:
- an exception
- available only on one backend
isn't really going to have traction.

**Comment by nursix** [comment]
Yup, I expected such an answer.

Unfortunately, though, these queries are generated from fairly complex, user-controlled filters, and are not standalone but just a part of the overall query - so that "crafting our own query" is not an option (would be much more complex than to have an additional operator in PyDAL).

Nor can we actually hardcode to one specific back-end either - the same filters should work on any database back-end, of course (even if not accent-insensitive then).

Accent-insensitive search is only an exception in English - in almost every other language this is a highly desirable feature. Is PyDAL limited to the needs of a certain locale? Or is it international?

But ok, I hear you - no much help can be expected for this case :/ Nevermind.

**Comment by nursix** [comment]
Note that PostGIS operators are also back-end specific and certainly less common a case than accent-insensitive search - and yet they are available in PyDAL ;) so this may not be as sharp an argument as it seems.

Maybe it comes down to who gets paid for it ;)

**Comment by niphlod** [comment]
As for cratfing your own, you can

db(db.table.name == 'test')('your specific piece backend-specific').select()

as for postgis, you're right, but at least it can be ported to other backends that support (or will support) GIS operations. 

Accent-insensitivity instead is not a standard and backend specific, i.e. in mssql you'd need a different collation on the db (or on the index), in oracle it's either a different collation or a command issued in the connection, etc etc etc.
The real hard problem you're asking to solve in the end is that If you really require backend-"freenes", you'd need to store the accent-insensitive version of the record on another column and query that one.

**Comment by nursix** [comment]
Hmm, yes - I know that sub-querying a Set would be the way, but as I say, it's not an option for us. The mechanism we use to construct the DAL Query is a lot more complex than that - and how could I possibly implement an OR with other parts of the query without replicating those parts as SQL string too?

The effort necessary to do that would come close to re-implementing the postgres adapter, which is economically complete nonsense if there is a possibility that we can just extend the existing one.

Therefore my idea to treat "unaccent" just the same way as "postgis" - as a back-end specific option - and to ignore it for back-ends which don't support it. I'd be happy to do this myself (yeees, I would get paid for it), but I would be grateful for some pointers how this is expected to be done so that it would be acceptable upstream? I don't want a custom PyDAL (and don't want to be forced to make one).

**Comment by nursix** [comment]
Aaaand...my current implementation is using REGEX with character alternatives in groups, which could, obviously, be the fallback for all back-ends which don't provide an accent-insensitive extension ;) So, it doesn't have to be a back-end specific operator.

I have considered collations before, but there is a catch: the specific deployments that need accent-insensitive search are all multi-locale (and I mean "multi" here: 20+ or more), so we would need to craft our own collation to cover them all :/

The option to store accent-free variants of the field content and use that for indexing and filtering has also come to my mind - but we're talking about a hundred different models here each with 2-5 different fields, so a generalization of the pattern is definitely required. So, even if that would obviously be the most scalable variant, it would also be by far the worst in view of maintainability.

We can not really look into bigger efforts here as we have relatively tight budget constraints, and especially we do not have weeks or months to get it working. Doesn't make your suggestions anyhow wrong, though - very appreciated.

**Comment by oscarfonts** [comment]
I was looking for accent-insensitive test searches and ended up here. And folowing @nursix suggestions, wrote a CustomPostgreSQLAdapter that overwrites the "CONTAINS" operation. It detects if unaccent extension is present and applies it.

Probably not perfect, but let me share, just in case someone else needs it:

```python
# -*- coding: utf-8 -*-/
from pydal.adapters import ADAPTERS, PostgreSQLAdapter
from pydal.objects import Expression

class CustomPostgreSQLAdapter(PostgreSQLAdapter):

    installed_extensions = None

    def has_extension(self, name):
        if self.installed_extensions is None:
            installed_extensions = [row[0] for row in self.db.executesql('select extname from pg_extension;')]
        return name in installed_extensions

    def UNACCENT(self, first):
        return 'UNACCENT(%s)' % self.expand(first) if self.has_extension('unaccent') else first

    def CONTAINS(self, first, second, case_sensitive=True):
        if self.has_extension('unaccent') and first.type in ('string', 'text', 'json'):
            first = Expression(first.db, self.UNACCENT, first, None, first.type)
            second = Expression(first.db, self.UNACCENT, self.represent(second, 'string'), None, first.type)
        return super(CustomPostgreSQLAdapter, self).CONTAINS(first, second, case_sensitive)

ADAPTERS.update({
    'custompostgres': CustomPostgreSQLAdapter
})
```

**Comment by nursix** [comment]
Thanks @oscarfonts, good stuff :)

We had considered that as an option - although it would have to be consistent across backends, and it would have to be a LIKE rather than CONTAINS, and it should be optional per query (because it's a multi-tenancy application where some users need it, others don't want it). Can all be solved based on your technique, of course.

Meanwhile, we have worked around the problem with a regex technique, which works well for our case and allows configuration - but then, as it happens, the requirement stakeholders changed their minds and dropped it, so for now we have no need to pursue this any further.

Thanks for sharing, however :)

**Comment by gi0baro** [comment]
@oscarfonts @nursix please note that the shared adapter is not yet compatible with pyDAL versions >= 16.06
