### ISSUE TITLE
bug in validate_and_update in case of json type field update

### ISSUE THREAD

**Issue by manuelep** [web2py/pydal#274]
# Test

+ Just create a brand new application (let's call it **test**) and add the following line in the model after the db definition in order to define a table with a json type field:
```python
db.define_table('tt', Field('aa', 'json', default={}))
```

+ save the modified file and go to the console.

+ open a python interpreter with the environment of the new app:
```bash
./web2py.py -S test -M
```

+ import a required function:
```python
from gluon.serializers import json as json_dumper
```

+ insert a record using the **validate_and_update_or_insert** method:
```python
db.tt.validate_and_update_or_insert(db.tt.id==1, aa=json_dumper({'a' : 1, 'b' : 0}))
db.commit()
```
this command will return this output: `<Row {'errors': {}, 'id': 1}>`

+ test the inserted value:
```python
type(db.tt[1].aa)
```
and it returns: `dict`

+ update the same record always using the **validate_and_update_or_insert** method:
```python
db.tt.validate_and_update_or_insert(db.tt.id==1, aa=json_dumper({'a' : 1, 'b' : 1}))
db.commit()
```

+ test the updated value:
```python
type(db.tt[1].aa)
```
and it returns: `unicode`

# Notes

+ First of all I would expect to run **validate_and_update_or_insert** method **WITHOUT** encoding my value destinated to the json type field just like I do in insert and update basic method, but the validation point me to use a json encoded value... anyway...
+ encoding the value when I insert the method works as expected but **when I repeat the operation performing an update the value is saved at the database level as a json encoded string** (not a json encoded object as in the case before).
+ I tested in the same way with SQLite (that has a db driver without a native json support) and PostgreSQL (with native json support)

Thank you
Best regards

    Manuele

**Comment by stephenrauch** [comment]
You might try this:

db.tt.validate_and_update_or_insert(db.tt.id==1, aa={'a' : 1, 'b' : 1})

**Comment by manuelep** [comment]
As I said it was the first option I tried "but the validation point me to use a json encoded value", in other words it returns:
`<Row {'errors': {'aa': 'Invalid json'}, 'id': None}`

**Comment by stephenrauch** [comment]
I was unable to duplicate this using only pydal (no web2py).  When trying to do validate_and_update_or_insert() I was receiving an error of:

```
AttributeError: 'Table' object has no attribute '_primarykey'
```

By adding ``_key='id'`` I was able to get the following to work (both prints returned 'dict'):

```python
db = DAL(DEFAULT_URI, check_reserved=['all'])
db.define_table('tt', Field('aa', 'json', default={}),)
db.tt.validate_and_update_or_insert(_key='id', id=1, aa={'a' : 1, 'b' : 0})
db.commit()
print(type(db.tt[1].aa))
db.tt.validate_and_update_or_insert(id==1, aa={'a' : 1, 'b' : 1})
db.commit()
print(type(db.tt[1].aa))
db.tt.drop()
db.close()
```

**Comment by mdipierro** [comment]
> type(db.tt[1].aa)
> and it will returns: unicode

pydal on py27 should always return utf8, not unicode. This will be a problem soon or later.

**Comment by gi0baro** [comment]
@mdipierro I will inspect this in the next days.

**Comment by stephenrauch** [comment]
@manuelep

Using IS_JSON() from web2py was able to duplicate the need to convert the dict to json before submitting, but the type returned from a query was 'dict' after both 'insert' and 'update'.

```python
db = DAL(DEFAULT_URI, check_reserved=['all'])
db.define_table('tt', Field('aa', 'json', requires=IS_JSON(), default={}),)
db.tt.validate_and_update_or_insert(db.tt.id==1, aa=simplejson.dumps({'a' : 1, 'b' : 0}))
print(type(db.tt[1].aa), (db.tt[1].aa))
db.tt.validate_and_update_or_insert(db.tt.id==1, aa=simplejson.dumps({'a' : 1, 'b' : 1}))
print(type(db.tt[1].aa), (db.tt[1].aa))
```

returned:

```
<class 'dict'> {'b': 0, 'a': 1}
<class 'dict'> {'b': 1, 'a': 1}
```

So, it appears you could possibly replace the validator to get your desired behavior of submitting a dict instead of a string.

**Comment by manuelep** [comment]
another information I can add is the framework version I used...
2.11.2-stable+timestamp.2015.05.30.11.29.46 (Running on Rocket 1.2.6, Python 2.7.5+)
and the exact commit is: b86184fe581274cfb0b750471cc0f3d8a7c1baf6
ASAP I'll try to write a little test script to run under different versions in order to isolate the problem.

**Comment by manuelep** [comment]
Have a look at this unittest that can help on understand the problem:
https://gist.github.com/5ca405dabb6c0563c892.git
Two considerations:
1. The [output problem](https://gist.github.com/manuelep/5ca405dabb6c0563c892#file-test_validate_and_update_or_insert_with_json_field-py-L51) comes out adding the validator IS_JSON and web2py do it for you by default.
2. To avoid the unwanted behaviour to need json object serialization is necessary to remove the IS_JSON validator.

So at the moment the best way to by-pass the bug is to remove (at least just before calling the validate_and_update_or_insert method) the json field default validator.

**Comment by gi0baro** [comment]
@mdipierro maybe this should be moved to web2py?

**Comment by ourway** [comment]
Any updates on this issue?  who's the culprit? web2py or pydal?

**Comment by gi0baro** [comment]
@ourway I think it's web2py related. @mdipierro @niphlod comments?

**Comment by mdipierro** [comment]
I have given some thought to this and I think we should leave this alone. JSON does not handle bytes. It only handles bytecode strings. the error is that users are putting str in import where there should be unicode. Web2py does the right thing: it converts str in unicode when storing them.
