### ISSUE TITLE
iterselect loses track of iterating cursor 

### ISSUE THREAD

**Issue by timrichardson** [web2py/pydal#288]
While iterating over iterselect, the iteration terminates if an update query occurs

# iterates only once
```python
for p in db(db.ul_product_cache.id>0).iterselect():
    product = json.loads(p['jsondata'])
    db.prototypes.update_or_insert(db.prototypes.Prototype ==
                            product['ProductGroup']['GroupName'],
    Prototype = product['ProductGroup']['GroupName'],
            origin='Unleashed')
```

```python
# iterates over everything
for p in db(db.ul_product_cache.id>0).iterselect():
    product = json.loads(p['jsondata'])
```

https://groups.google.com/forum/#!topic/web2py-developers/kxGnh1qlpQ8
suggestion from Paolo is:

I'm not in the condition to run deep tests, however, I guess the problem is related to the execution of the inner query (update_or_insert).
Have a look at https://github.com/web2py/pydal/blob/master/pydal/objects.py#L2714, the next() method calls self.db._adapter._fetchone(), which calls cursor.fetchone()
Essentially, by running the inner query, you are overriding the original cursor with the unexpected result you got.

**Comment by gi0baro** [comment]
@ilvalle how should we fix this? implementing a cursor stack? :/

**Comment by ilvalle** [comment]
Multiple cursors means multiple connections and at a first sight it isn't a that easy. I'll think about a possible approach and I'll return with some thoughts.
