### ISSUE TITLE
Support ST_X and ST_Y function on POSTGIS geography() fields

### ISSUE THREAD

**Issue by wish7code** [web2py/pydal#298]
Currently lat/lon queries using ST_X and ST_Y on geography fields fails with

Example db.py:
Field.Virtual('lat', lambda row: db(db.my_table.id == row.my_table.id).select(db.my_table.the_geog.st_y()).first()[db.my_table.the_geog.st_y()]),

'<class 'psycopg2.ProgrammingError'> function st_x(geography) does not exist LINE 1: SELECT ST_X(my_table.the_geog) FROM my_tableWHERE (r... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. '

Could you add ST_X and ST_Y methods for geography fields too (geometry fields already implemented)?

Let me know in case you need further details,

Thanks & cheers
Toby

Reference mailing list discussion:
https://groups.google.com/forum/#!topic/web2py/Fy4ciHb_5MY

**Comment by mdipierro** [comment]
psycopg2.ProgrammingError is a postgres error, not a web2py/pydal error. There is nothing we can do for this.
