### ISSUE TITLE
fails on python2 when folder set

### ISSUE THREAD

**Issue by simonm3** [web2py/pydal#300]
The default pickle protocol in python3 is 3 but this is not compatible with python2. If pydal could set protocol 2 then databases created by a python3 application can be accessed by a python2 application.

Otherwise when you try to access a database created in python3 from a python2 application you get:
ValueError: unsupported pickle protocol: 3

**Comment by niphlod** [comment]
why would you need to use the same folder with py2 and py3 code !??!?!?!?!?

**Comment by simonm3** [comment]
It is a database so it might be accessed by more than one application.

Or you are migrating to py3 in stages.

Or you are trying to maintain code that is written to work on py2 and py3.

**Comment by niphlod** [comment]
yes, but in that case only ONE (and it's the recommended way to do it) needs to have migrate=True. All the other should be set to migrate=False, and no .table whatsoever are needed.

**Comment by gi0baro** [comment]
may I close this?

**Comment by niphlod** [comment]
IMHO yes. ok for being able to work with py2 OR py3, but hoping for that OR to be an AND is out-of-scope.

**Comment by gi0baro** [comment]
@simonm3 I agree with @niphlod. Since the only *real* condition to have this error is to downgrade application code from python3 to python2 (condition that should never happen ^^") I'm gonna close this.
