### ISSUE TITLE
Error calling method field or virtual field inside a virtual field

### ISSUE THREAD

**Issue by cccaballero** [web2py/pydal#304]
This are the cases when the problem occours:

    db.business.test = Field.Virtual(lambda row: 4)
    db.business.testa = Field.Virtual(lambda row: row.business.test)
    print db(db.business.id > 0).select().first().testa

    db.business.test = Field.Method(lambda row: 4)
    db.business.testa = Field.Virtual(lambda row: row.business.test())
    print db(db.business.id > 0).select().first().testa

and works with:

    db.business.test = Field.Virtual(lambda row: 4)
    db.business.testa = Field.Method(lambda row: row.business.test)
    print db(db.business.id > 0).select().first().testa()

    db.business.test = Field.Method(lambda row: 4)
    db.business.testa = Field.Method(lambda row: row.business.test())
    print db(db.business.id > 0).select().first().testa()

**Comment by gi0baro** [comment]
This is because you shouldn't set virtual fields and methods setting attributes directly. If you use `define_table` all the examples you given will work:

```python
db.define_table(
    'business',
    Field.Virtual('test', lambda row: 4),
    Field.Virtual('testa', lambda row: row.business.test)
)
```

**Comment by gi0baro** [comment]
**Correction:** all the examples you given will work except the one when you try to invoke a `Field.Method` from a `Field.Virtual`. pyDAL loads virtual fields before methods, with the order you specified in the `define_table` method.
Since the design principle behind `Field.Method` is to be *on demand*, would be pointless to invoke a method from a virtual.

**Comment by cccaballero** [comment]
Many thanks for your answer, I was using that way trying to achieve a similar approach to a object oriented model, now I need to declare "functions" before the "variables", because a more big function can't be inside lambda, something like:

    def test(row):
        return 4

    def testa(row):
        return row.business.test

    db.define_table(
        'business',
        Field.Virtual('test', test),
        Field.Virtual('testa', testa)
    )

It feels so unnatural...
