### ISSUE TITLE
crashes on python 3.5 on windows

### ISSUE THREAD

**Issue by simonm3** [web2py/pydal#310]
Can create a DAL but when one does define_table("temp") it says "python has stopped working".

Worked fine on previous python3 and python2 installations.

**Comment by gi0baro** [comment]
Just tried on linux & osx with python 3.5 and it works.
Seems related to windows only.

@niphlod any ideas on this?

**Comment by cassiobotaro** [comment]
@simonm3 what version  of windows ?

**Comment by niphlod** [comment]
appveyor is testing 3.4 . I'll see if 3.5 can be added.

**Comment by simonm3** [comment]
Windows 10

**Comment by simonm3** [comment]
The problem is with the latest anaconda distribution.

The previous anaconda version was based on python 3.4. If I install a
python 3.5 conda environment on this then pydal works fine. However the
most recent anaconda distributuion based on 3.5 crashes with pydal. Perhaps
there is a conflicting package somewhere?

**Comment by michele-comitini** [comment]
which db and adapter?

**Comment by simonm3** [comment]
I only tried sqlite

**Comment by simonm3** [comment]
I believe this is a problem with pywin32  on windows 10 as it seems to be on call to portalocker which crashes on the line win32file._get_osfhandle

Have logged it here. However perhaps there is a workaround by changing pydal to avoid calling portalocker. Not sure what this code does?
https://sourceforge.net/p/pywin32/bugs/711/

**Comment by niphlod** [comment]
@simonm3 : can you see if with the latest build of pywin32 the problem is solved on your env ? 2016-01-11 is the latest available build for pywin32

**Comment by simonm3** [comment]
Yes it works. Anaconda is  not using latest yet but I installed separately




On 8 March 2016, at 21:42, niphlod <notifications@github.com> wrote:

@simonm3 : can you see if with the latest build of pywin32 the problem is solved on your env ? 2016-01-11 is the latest available build for pywin32

**Comment by gi0baro** [comment]
I'm closing this.
