### ISSUE TITLE
How to create compound index on MongoDB using pydal?

### ISSUE THREAD

**Issue by kmcheung12** [web2py/pydal#313]
In mongodb's python driver `pymongo`, one can create compound index by

    my_collection.create_index([("mike", pymongo.DESCENDING),
                                ("eliot", pymongo.ASCENDING)])

Is such feature supported by pydal? 
if so can someone kindly provide an example?

**Comment by stephenrauch** [comment]
[From the book:](http://web2py.com/book/default/chapter/06#Indexes)

> _Currently the DAL API does not provide a command to create indexes on tables, but this can be done using the executesql command._

However, executesql does nothing useful on the mongo driver.

**Comment by kmcheung12** [comment]
Thanks for clarifying!

**Comment by gi0baro** [comment]
@kmcheung12 btw, you can still access the driver using

```python
db._adapter.connection.my_collection.create_index([
    ("mike", pymongo.DESCENDING),
    ("eliot", pymongo.ASCENDING)])
```

**Comment by kmcheung12** [comment]
Thanks for the info! I'm experimenting with different db backend that I want to be able to create index on certain key. If I run 

    db._adapter.connection.my_collection.create_index([
        ("mike", pymongo.DESCENDING),
        ("eliot", pymongo.ASCENDING)])

The models will become db specific and when switching to other db, these lines need to be removed. Is my understanding correct?

**Comment by gi0baro** [comment]
@kmcheung12 the snippet refers specifically to pymongo.
In fact, `db._adapter.connection` is a pointer to the real driver actually.

Indexing support by pyDAL should comes with the next version, so stay tuned :)
