### ISSUE TITLE
Manual upload fails when db.table.field.store returns unicode

### ISSUE THREAD

**Issue by pembeci** [web2py/pydal#319]
[Moved from web2py/web2py#1131]

When I tried manual upload [as described in the book](http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer#More-on-uploads), there was an error although the file was copied to the application `uploads` folder. I noticed that for some reason `db.table.field.store` was returning a `unicode` string on my system instead of `str` as the new filename. So I believe [this part of the codebase](https://github.com/web2py/pydal/blob/3131f834ef0e4176a54944516269da3683243713/pydal/objects.py#L689-L693 ) will be corrected like this (modified per @cassiobotaro's suggestion):

```python
def _attempt_upload(self, fields):
        for field in self:
            if field.type == 'upload' and field.name in fields:
                value = fields[field.name]
                # if not (value is None or isinstance(value, str)):
                if not (value is None or isinstance(value, basestring):
```

**Comment by gi0baro** [comment]
@pembeci @cassiobotaro I'm not sure the error is in that line. Will inspect this accurately in the next days.
