### ISSUE TITLE
issue with ._before_update() and ._before_delete()

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/pydal#330]
There is something wrong with:

https://github.com/web2py/pydal/blob/dcfb5f58aa1ff1c87b349c31e67f14a4d9774ebe/pydal/objects.py#L245

Probably in delete_uploaded_files():
https://github.com/web2py/pydal/blob/dcfb5f58aa1ff1c87b349c31e67f14a4d9774ebe/pydal/objects.py#L2101

I have upload field image files that get deleted from hard drive on form update for no reason. Field is not even include in form as it is in readable=, writable=False, so not updated by the form, so field should stay untouched. Files are stored on drive (not in db) and files names stays in upload field in the backend only files get remove... In addition this doesn't happen to all the upload fields on the table... Only the field with compute used to get the image resized...

Here models definition:
```python
Field('picture', 'upload', 
    uploadseparate=True, 
    autodelete=True, 
    label=T('Profile image'),
       represent=lambda value, row: image_chooser(value, row, '360px', '360px')
       ),
Field('address_book_picture', 'upload', 
    uploadseparate=True, 
    autodelete=True,
    compute=lambda row: 
    image_utils.SMARTHUMB(row.picture,
        'picture',
        (115, 100),
        name='address_book_thumb',
        db=db),
    represent=lambda value, row: image_chooser(value, row, '115px', '100px')
    ),
Field('profile_picture', 'upload', 
    uploadseparate=True, 
    autodelete=True,
    compute=lambda row: 
        image_utils.SMARTHUMB(row.picture, 
            'picture',
            (360, 360),
            name='profile_thumb',
            db=db), 
...
    )
```

When I remove the call to delete_uploaded_files() at line 245 and 246 issue doesn't happen... Or if I remove the compute() it doesn't happen either...

I can't investigate more right now, but will add comment to this issue and submit PR if I am able to find the root cause and fix it.

Thanks

Note: I need these compute() to derive thumbnails from picture field...

**UPDATE:**

The faultive line:
https://github.com/web2py/pydal/blob/dcfb5f58aa1ff1c87b349c31e67f14a4d9774ebe/pydal/objects.py#L2107

When I comment it issue goes away...

Not sure I understand the rational behind appending any compute fields...

**Comment by BuhtigithuB** [comment]
Note: I need these compute() to derive thumbnails from picture field...

**Comment by gi0baro** [comment]
@niphlod any ideas on this?

**Comment by remcoboerma** [comment]
@BuhtigithuB can you insert raising an exception at that point and post the traceback here?

**Comment by BuhtigithuB** [comment]
I try to reproduce de problem with a dummy app... and I failed... And I
seems to have another problem I get partial traceback complaining about
missing "id" when I submit "blank" (no change in my form) update form...
The problem occur with a custom form, so I guess there is something wrong
with it. The thing is that form has always worked since many year and I
have search and search what could be wrong without success.

So, since I can't reproduce with a standard SQLFORM and that the _thumnail_
compute upload field behave just right we may close this ticket...

I will reopen it if I found anything related latter...

Sorry for false positive.

**Comment by BuhtigithuB** [comment]
This ticket can definitely be closed... I had found the root cause of my issue in the fact that record id was not include in the custom form that seems to start causing problem only recently, maybe because I had versioning over auth_user table and this issue run out without being noticed by me...

Thanks

**Comment by BuhtigithuB** [comment]
Close
