### ISSUE TITLE
Table.truncate fails

### ISSUE THREAD

**Issue by nursix** [web2py/pydal#353]
Table.truncate() has a default parameter `mode=None`, which overrides the default of `''` in SQLAdapter.truncate(), and hence produces a query like:

    TRUNCATE TABLE TablenameNone

i.e. appending the `None` to the tablename. Of course that leads to a 

    ProgrammingError: (1146, "Table 'TablenameNone' doesn't exist")

Shouldn't the default in Table.truncate() be `''` as well then? Or does one have to specify a `mode=''` explicitly for Table.truncate()?

**Comment by gi0baro** [comment]
@nursix Hmm. This is not changed recently. 

@mdipierro this is a long-living bug. Strange nobody noticed this.

**Comment by nursix** [comment]
Well, it kinda has changed recently.

If you compare the original 16.03 variant:
https://github.com/web2py/pydal/blob/60e97e7cfd1da98f3cf38b2023965226d42e5e5b/pydal/adapters/base.py#L995

...with the current variant:
https://github.com/web2py/pydal/blob/master/pydal/dialects/base.py#L428

...then you can see that small difference `mode or ''` (which catches the None from Table.truncate) vs. just `mode` (which stringifies it instead).

We've had our unit tests running some truncates for quite some time (>2years), and it always worked - but fails now after the restructuring of PyDAL (along with many other of our functions, which broke due to the restructuring - isn't quite backwards-compatible a change ;) ).

**Comment by gi0baro** [comment]
@nursix you're right. I will re-check the flow to decide how to fix this.
