### ISSUE TITLE
"datetime" field type translated as TIMESTAMP SQL Type

### ISSUE THREAD

**Issue by nursix** [web2py/pydal#376]
Why is this no longer DATETIME?

This shows quite odd behavior in MySQL: the first datetime field receives a default value (current date/time), and an update constraint (again, current datetime), and it is impossible to set it to None (because that just sets it back to the current date).

That breaks a lot of our functionality that operates with datetime fields (all of our tables do) - and it is quite unexpected a change.

Shouldn't the "TIMESTAMP" type be a separate field type if it is desired, and "datetime" be left as it was before?

**Comment by nursix** [comment]
(Issue above only relates to MySQL, for all other adapters TIMESTAMP seems just fine - but MySQL is really odd with this)

**Comment by nursix** [comment]
NB Adding

    @sqltype_for('datetime')
    def type_datetime(self):
        return 'DATETIME'

to the Mysql dialect promptly fixes the problems (as expected) - but now I don't know what the idea was behind that change, so wouldn't send a PR.

Previously, the MySQL Adapter used DATETIME for "datetime":
https://github.com/web2py/pydal/blob/60e97e7cfd1da98f3cf38b2023965226d42e5e5b/pydal/adapters/mysql.py

I'm not sure that the MySQL-specific behavior for TIMESTAMP is desirable for the "datetime" field type - but if it is for the majority, then at least there should be some sort of workaround for the implicit default/update constraints, otherwise it is very inconsistent with other adapters.

**Comment by gi0baro** [comment]
@nursix this is probably a typo I did in the refactoring. Will check this out and fix it asap.

**Comment by nursix** [comment]
That would be great, thank you.
