### ISSUE TITLE
upload_in_blob adapter parameter

### ISSUE THREAD

**Issue by mdipierro** [web2py/pydal#38]
https://code.google.com/p/web2py/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Summary%20Modified&groupby=&sort=-modified&id=1935#makechanges

**Comment by gi0baro** [comment]
We need the list of the adapters on which we want to implement this.

Should be easy to reproduce as I did on the `mongodb` adapter.

**Comment by niphlod** [comment]
now it's https://github.com/web2py/web2py/issues/707

**Comment by gi0baro** [comment]
Actually since this only involves pyDAL code I actually think web2py#707 should be closed and processed here.

**Comment by niphlod** [comment]
yep. leave it there a couple of days just to cut some slack to whoever followed the issue on googlecode from being redirected 2444543times in one day. there are other open issues regarding DAL that will need transfered here

**Comment by gi0baro** [comment]
@niphlod I can do this, but before start coding I need to know if upload using blobs is supported by any adapter. If not, can we build a list?

**Comment by niphlod** [comment]
uhm. it's kinda simple.... if anybody didn't raise a problem for any adapter until now is because uploads in blob are working. If they're not working, this "addition" won't work for sure. 

IMHO the issue consists in changing the behaviour ..... if up until now 

    Field('upfield', ...., uploadfield='theblob')
    Field('theblob', 'blob')

this is a request to have the simpler model

    Field('upfield')

behave like what you'd get now doing

    Field('upfield', uploadfield='upfield_blob')
    Field('upfield_blob', 'blob')

**Comment by gi0baro** [comment]
@niphlod https://github.com/web2py/pydal/pull/50 is this what you were thinking about?

**Comment by niphlod** [comment]
frankly, as with ALL the other issues coming from googlecode, I'm not the OP, but I'm glad I get called to review PRs :-P. the original discussion is [here](https://groups.google.com/forum/#!msg/web2py/33Qy9-xpokA/URIB_LXEUQIJ) and @abastardi is the original proposer for the feature.

If I see correctly (but after 16 hours on a monitor I could very well be wrong) it's a good start but still missing the machinery:
-  to create automagically the blob field
- making the original 'upload' field store aware that it should store content in that column

**Comment by gi0baro** [comment]
I've looked around this https://github.com/web2py/pydal/blob/master/pydal/objects.py#L337 and I think we already got the *machinery*. Also because it was working on mongo just with the `uploads_in_blob` parameter.

**Comment by niphlod** [comment]
my bad. I need to familiarize with the new structure in order to be able to search/see what I'm looking for. Seems that the only thing left is to add a test and update the book accordingly.

**Comment by gi0baro** [comment]
Ok, I'm going to merge #50
