### ISSUE TITLE
Query Not Supported: %d format: a number is required, not str error in grid

### ISSUE THREAD

**Issue by timrichardson** [web2py/pydal#382]
A recent upgrade is causing pagination errors on the grid. 
The error string "Query Not Supported: %d format: a number is required, not str" is returned, but not exception is raised.

This is with mssql3 adapter. It occurs when I choose a specific page, or the next page, on a grid. 
web2py is R-2.14.6

gluon/packages/dal is master freshly pulled. 
The problem is in the DAL. As a crude bisect, leaving the web2py version as above, it works with tagged DAL release v15.09, v15.12, v16.03 but broke by v16.06

**Comment by niphlod** [comment]
Is there a specific reason to use mssql3 over mssql4?
Imho the problem is a recent rewrite of the trick that paginates on mssql3
Il 23 giu 2016 03:24, "Tim Richardson" <notifications@github.com> ha
scritto:

**Comment by timrichardson** [comment]
I didn't know about mssql4. However, when I change mssql3 to mssql4 in the connection string, but staying with DAL 16.03, moving to another page causes "Query Not Supported: ('42000', "[42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near 'OFFSET'. (102) (SQLExecDirectW); [42000] [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid usage of the option NEXT in the FETCH statement. (153)".
I also see this when using master for DAL.

**Comment by gi0baro** [comment]
@timrichardson @niphlod will inspect this asap.

**Comment by gi0baro** [comment]
@timrichardson I'm not really sure this is a pyDAL bug. Would be nice to have a stacktrace of what's happening, because I think the grid is pushing wrong queries to pyDAL.

**Comment by niphlod** [comment]
a small recap for everybody:
mssql4 uses features available from 2012 onwards to allow faster paging: if you're on 2012,2014,2016, mssql4 is the way to go, no questions asked.
mssql3 uses a trick similar to what oracle does (wrapping the actual set in an inner query), but it can be used from 2005 onwards (so 2005, 2008, 2008R2 in addition, of course, to 2012,2014,2016)
mssql is for everything older than 2005, so REEEEEALLLY not to use if not strictly required.

the "n" bit (mssql3n, mssql4n) is if you want to use unicode everywhere, which should be the case for all modern apps.
I'll have some time to spare this weekend to see what's going on under the hood if anyone doesn't pinpoint it.

**Comment by timrichardson** [comment]
Why is it not an exception, by the way (i.e. it does not generates a traceback)

**Comment by gi0baro** [comment]
@niphlod do you confirm we have tests for pagination on mssql? if this is true, and they passes, I would recommend to inspect the grid code to ensure it's not generating invalid queries from web2py side.

**Comment by niphlod** [comment]
nope, we don't test mssql3. I'll take a look either way.
