### ISSUE TITLE
Problem with 'json' fields in Postgres

### ISSUE THREAD

**Issue by nursix** [web2py/pydal#383]
In previous PyDAL versions, select of a 'json' type field would return the value as object - both with MySQL (no native JSON support) and Postgres (with native JSON support):

```
>>> table = db.define_table("test", Field("test", "json"))
>>> table.insert(test={"a":1})
1L
>>> row = db(table.id==1).select(limitby=(0,1)).first()
>>> row
<Row {'test': {u'a': 1}, 'id': 1L}>
```

Strangely, with 16.06, select still returns the object for MySQL (no native JSON support), but a string for Postgres (with native JSON support):

```
>>> table = db.define_table("test", Field("test", "json"))
>>> table.insert(test={"a":1})
1L
>>> row = db(table.id==1).select(limitby=(0,1)).first()
>>> row
<Row {'test': '{"a": 1}', 'id': 1L}>
```

Bug or deliberate change?

Shouldn't a 'json' type field always both accept and return the original object?

And how can I handle this inconsistency in the IS_JSON validator as we can no longer introspect the native JSON capabilities of the current adapter (used to be db._adapter.driver_auto_json, but that doesn't exist anymore)?

**Comment by nursix** [comment]
...and why would it return a string /with/ native JSON support, but an object without? (doesn't quite make so much sense to me - if it had to be inconsistent, then shouldn't it at least be the other way around?)

**Comment by gi0baro** [comment]
@nursix this is not a deliberate change. Can you post which version of the adapter you're using and the postgre version? Will inspect this asap.

**Comment by nursix** [comment]
pydal.adapters.postgres.PostgrePsyco, 16.07-dev (=current trunk version)

psycopg2 Version 2.5.2, PostgreSQL-9.1.9

So indeed that is postgres without native JSON, but still inconsistent and an unexpected change.

**Comment by gi0baro** [comment]
@nursix can you log the output of:

```python
db._adapter.dialect
db._adapter.parser
```

Probably there's something wrong with the parser configuration.

**Comment by nursix** [comment]
<pydal.dialects.postgre.PostgreDialect object at 0x3335f10>
<pydal.parsers.postgre.PostgreAutoJSONParser object at 0x2ae4150>

**Comment by nursix** [comment]
@gi0baro So is it indeed so that in 16.06 the json type should always accept and return the object regardless of the native JSON capabilities of the backend? Or do I need to introspect native JSON capabilities and adapt the handling of the field accordingly - and if so, then how would I do this now?

Also thanks for looking into the underlying problem, of course :)

**Comment by gi0baro** [comment]
@nursix the problem seems the check of the json parsing. Seems pyDAL 16.06 expects json values from the driver while it returns strings. I gonna perform some additional checks, probably we'll release a new bugfix version next week. In the meantime you can check if this fix your problem:

```python
db = DAL('youruri')
# just after the db instance creation
from pydal.parsers.postgre import PostgreParser
db._adapter.parser = PostgreParser(db._adapter)
```

**Comment by nursix** [comment]
It seems that this fixes the problem for my local config (pg-9.1), but obviously that does not work with pg-9.2 now ;) (need to support all versions 9.1=>9.4)

There is no urgency with the fix - but if you could answer the questions in my previous comment, that would be of great help.

**Comment by gi0baro** [comment]
@nursix no you don't have to introspect the JSON capabilities of the backend.
This is a pyDAL feature since very old versions (at least until I've broken it), so that on postgres >= 9.2 it will use *json* columns, while on the old ones use *text* columns. 
pyDAL will automatically parse the the strings on this old versions to re-build the original json objects for you, while on the the new ones it relies on the driver for its native support.
On pyDAL 16.06 this doesn't work anymore because it's not matching the driver version with the postgres version.

**Comment by nursix** [comment]
Ok, thanks - so then it's all as I expected it.
