### ISSUE TITLE
officially deprecate db().select(...) shortcut

### ISSUE THREAD

**Issue by niphlod** [web2py/pydal#388]
Due mainly to:
 - different shortcomings
 - no clear path on how to solve them
 - endless and repeated discussions leading nowhere

I hereby take the responsibility to log the issue tracking substantially an NB: on the book and on the changelog of pydal that will OFFICIALLY DEPRECATE the shortcut.

reference: https://github.com/web2py/web2py/issues/740

**Comment by gi0baro** [comment]
+1

**Comment by mdipierro** [comment]
Should I update the book or will you?

**Comment by niphlod** [comment]
https://github.com/web2py/web2py-book/issues/346 has been logged, so we can do spring-cleaning here
