### ISSUE TITLE
Feature request: field type "list:float" or "list:double"

### ISSUE THREAD

**Issue by Kopachris** [web2py/pydal#390]
The only databases I'm really familiar with are MySQL, and SQLite, but I can't think of any technical reasons why a "list:double" type can't work just like "list:integer" does. Seems like a bit of an oversight that there isn't already such a type. It looks like I should be able to simply:
- Add a method `bar_decode_double(value)` in `helpers/methods.py`
- Add a method `ListsParser._list_doubles(self, value)` in `parsers/base.py`
- Add two methods, `SQLDialect.type_list_double(self)` and `NoSQLDialect.type_list_double(self)`, in `dialects/base.py`
- Add two methods, `BaseRepresenter._list_double(self, value)` and `NoSQLRepresenter._list_double(self, value)`, in `representers/base.py`

If there aren't any technical objections, I'll make a fork and start working on adding a "list:double" type, and then issue a pull request. If I'm missing anything obvious, let me know.

**Comment by Kopachris** [comment]
I've just tested these modifications on a working copy of pydal I have on my work computer. For `sqlite:memory` at least, it appears to work as expected:

```
U:\>python
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (In
tel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> float('3.14159265358')
3.14159265358
>>> from pydal import DAL, Field
no file locking, you must install the win32 extensions from: http://sourceforge.
net/projects/pywin32/files/
>>> db = DAL('sqlite:memory')
>>> db.define_table('testdb', Field('testfl', 'list:double'))
<Table testdb (id, testfl)>
>>> db.testdb.insert(testfl=[0.5, 1.0, 1.5, 3.14159265358, -42.0007])
1
>>> db.commit()
>>> db.testdb[1]
<Row {'id': 1, 'testfl': [0.5, 1.0, 1.5, 3.14159265358, -42.0007]}>
>>> db.testdb[1].testfl
[0.5, 1.0, 1.5, 3.14159265358, -42.0007]
>>>
```

I'll commit these changes and do more testing when I get home from work.

**Comment by mdipierro** [comment]
I do not believe this should exist. The proper way to handle this is use a json field and put a list of float in there.

This is a NO NO db.testdb.testfl.contains(2.0) because of the way floats are compared. Exact comparisons only make sense for int and strings not for float numbers and we do not want to encourage bad practice.

**Comment by Kopachris** [comment]
Don't rounding errors affect comparisons with floats/doubles anyway?

**Comment by mdipierro** [comment]
yes. http://floating-point-gui.de/errors/comparison/
Why not use a json type instead?

**Comment by Kopachris** [comment]
Why not use a json type for list:integer or list:string? It doesn't make much sense to provide a generic form like 'list:xxx' to take advantage of various NoSQL options' native list types, but exclude lists of types that are supported by those same NoSQL flavors that would be easy to implement in SQL. web2py already allows comparisons on regular float/double columns, e.g. `db.foo.some_float == 3.14159` or `db.foo.some_float >= 1.0`. I don't see that this is really any different, or that it encourages bad practice (my `testfl.contains()` above was just an example to show that the list:double type worked).

If you're still against it, though, it might at least be worth a sentence in The web2py Book explaining that 'list:decimal' and 'list:float' will not be implemented in the DAL because of the rounding issues inherent to floating point calculations, and that a user should use json instead.

Personally, for my own use case (list of credit values supported by a slot machine), I think a list:decimal will work better anyway, and I'll work on adding that in my branch.

**Comment by mdipierro** [comment]
Let's here some more opinions on web2py developer about this. If other developers disagree with me, I am not vetoing this. I am just explaining why I never needed and I tend to prefer not to add things that can be done in other ways.

**Comment by michele-comitini** [comment]
if comparison is the issue then why not use decimal(n,m) type?
IMHO at db level list:<type>  should implement arrays where supported, a
one to many relation, json or whatever. Otherwise it can become an
interoperability nightmare when used from other applications accessing the
db.  Moreover the db server cannot do indexing so searching is all up to
the application and DAL (and very slow)

mic




2016-07-07 12:25 GMT+02:00 mdipierro <notifications@github.com>:

**Comment by mdipierro** [comment]
any objection to closing this as wont-fix?

**Comment by Kopachris** [comment]
No objection

**Comment by Kopachris** [comment]
No objection
