### ISSUE TITLE
TypeError: unhashable type: 'Field'

### ISSUE THREAD

**Issue by ilvalle** [web2py/pydal#392]
Running python 3.5 I got the following
```
>>> from pydal.objects import Field
>>> f=Field('test')
>>> f in {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'Field'
```
This snipped code is an example of what there is in web2py https://github.com/web2py/web2py/blob/master/gluon/sqlhtml.py#L80

**Comment by gi0baro** [comment]
I think this is related to changes to the built-in `object.__hash__` method in python 3 compared to python 2, as from https://docs.python.org/3/reference/datamodel.html#object.__hash__:

> A class that overrides `__eq__()` and does not define `__hash__()` will have its `__hash__()` implicitly set to `None`. When the `__hash__()` method of a class is `None`, instances of the class will raise an appropriate `TypeError` when a program attempts to retrieve their hash value, and will also be correctly identified as unhashable when checking `isinstance(obj, collections.Hashable)`.

`Field` inherits from `Expression` that does override `__eq__`.
I think a solution could be add to `Field` (but needs tests):

```python
def __hash__(self):
    return hash(str(self))
```

**Comment by gi0baro** [comment]
Additionally, a test regarding `__hash__` on current pyDAL, with python 2.7:

```python
>>> Post.title.__hash__
<method-wrapper '__hash__' of Field object at 0x1043a1f10>
>>> Post.title.__hash__()
272867825
```

and python 3.5
```python
>>> Post.title.__hash__
>>> Post.title.__hash__()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: 'NoneType' object is not callable
```

**Comment by ilvalle** [comment]
Initially, I thought to fix it adding
```    
def __hash__(self):
    return id(self)
```
However, for me is also ok in hashing the string representation.

**Comment by mdipierro** [comment]
I prefer the id(...) than hash(str(...))
