### ISSUE TITLE
upgrading web2py breaks use of executesql

### ISSUE THREAD

**Issue by remcoboerma** [web2py/pydal#396]
Before i could: 

```python

db.define_table('top_interrupts_by_frequency',
                Field('activity'),
                migrate=False,  # for a query
                primarykey=['activity']
                )

def top_interrupts_by_frequency(user_id, count=8, min_duration=2):
    dal_set = db.executesql('''
                select activity
                  from timetable
                 where client = ?
                   and ended is not null
                  and cast((julianday(ended) - julianday(started))*24*60*60  as integer) > ?
              group by activity
              order by count(activity) desc
                 limit {}
             '''.format(count), placeholders=(str(user_id), min_duration), fields=db.top_interrupts_by_frequency)
    return dal_set 
```

and in the controller have something like: 

```python
    top_interrupts = top_interrupts_by_frequency(auth.user_id)
    for row in top_interrupts:
        button = A('Int ', STRONG(row.activity), _class='btn btn-success btn-sm btn-outline',_role='button',_href=URL(f='cmd', vars=dict(command='i "{}"'.format(xmlescape(row.activity)))))
```

After upgrading (to 2.14.6-stable+timestamp.2016.05.09.19.18.48) this throws something ugly at my face: 

```text
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 220, in restricted
    exec(ccode, environment)
  File "/home/www-data/web2py/applications/timed/controllers/default.py", line 250, in <module>
  File "/home/www-data/web2py/gluon/globals.py", line 405, in <lambda>
    self._caller = lambda f: f()
  File "/home/www-data/web2py/gluon/tools.py", line 4297, in f
    return action(*a, **b)
  File "/home/www-data/web2py/applications/timed/controllers/default.py", line 119, in index
    button = A('Begin ',STRONG(row.activity), _class='btn btn-default btn-sm btn-outline',_role='button',_href=URL(f='cmd', vars=dict(command='on "{}"'.format(xmlescape(row.activity)))))
  File "/home/www-data/web2py/gluon/packages/dal/pydal/objects.py", line 91, in __getattr__
    raise AttributeError
AttributeError
```
with for the `__getattr__` call: 
```text
Function argument list
(self=<Row {'_extra': {'top_interrupts_by_frequency.activity': 'brk:Break'}}>, k='activity')
```

Trying to get any data out a record requires something like this: 
```python
row['top_interrupts_by_frequency.activity']
```
which you can imagine is quite unlike 
```python
row.activity
``` 
which i have used quite a bit. 
I've updated web2py to the latest, so that's the dal version used right now. I don't know exactly what version i came from. 

edit: new version of web2py added

**Comment by remcoboerma** [comment]
For anyone interested, here is a little helper that works for me: 
```python
def storageify_executesql_output(table, set):
    duup = lambda row:Storage({str(field):row['{}.{}'.format(table._tablename,str(field))] for field in table.fields})
    for dal_row in set:
        yield duup(dal_row)
```

usage: 

```python
def foo():
    table_ref = db.top_interrupts_by_frequency 
    dal_set = db.executesql('''
             <your sql here> 
             '''fields=table_ref) 
    return storageify_executesql_output(table_ref, dal_set)
```

**Comment by niphlod** [comment]
you like overcomplicating...(and format() on a string to pass a query?!?!? nooooo) 
BTW, "fields" of executesql is a list of fields, not sure that you can/will/need to rely on db.table to auto.unveil the fields... use db.tablename.ALL which is a better explicitation of the fields

**Comment by remcoboerma** [comment]
Thanks for sharing niphlod. From the book:

> The fields list can include one or more DAL Table objects in addition to or instead of including Field objects, or it can be just a single table (not in a list). In that case, the Field objects will be extracted from the table(s).

The `.format` could be a thingy, but it's save here. No user generated input ever comes near. Probably the speed of development. 

Anyway, it worked for months and months and now it breaks. There's no overcomplicating in that . Do you have any idea what could have caused it? Would be great to get a pointer.

**Comment by niphlod** [comment]
hey, don't shoot the messenger. probably @gi0baro can chime in but IMHO the rationale is that the resultset is the same for both single-table resultsets AND for multiple-tables joined resultsets.


BTW: this is not the case but "it worked for months" serves as "please fix it" ONLY if it's documented AND unittested (in practice, which turns into "for all matter and purposes"). In this specific case, I forgot about fields= being able to digest a db.sometable reference...but the resulting resultset is not explicitely indicated... I think it's just something that slipped in. let us check.

**Comment by niphlod** [comment]
confirmed, it slipped. checking the blamed commit....

**Comment by niphlod** [comment]
ok, found the culprit. in a hurry, set entity_quoting=False on the DAL() instance. 
executesql doesn't work with fields= and entity_quoting=True, which is the default since 16.06.
I'll post a PR with the fix (making entity_quoting True or False work with executesql) and all the regression tests I can think of.

**Comment by mdipierro** [comment]
We cannot break this syntax: row['tablename.fieldname'] it is critical in
many applucation. It avoids explucit check on wherher the row contain one
or more tables joined. It not a query in a string. If we broke it we need
restore it. A

**Comment by niphlod** [comment]
@mdipierro : solved and restored, although it behaves in the "usual" bi-faced way: a set containing one table results in a list of "dicts" with a key for each col, while a set containing two tables results in a list of dicts with a key for each table holding a dict with a key for each column.

**Comment by remcoboerma** [comment]
Thanks for the fix

**Comment by niphlod** [comment]
np, thanks for reporting ^_^

**Comment by mdipierro** [comment]
Thanks Simone!
