### ISSUE TITLE
Joinable subselects

### ISSUE THREAD

**Issue by nextghost** [web2py/pydal#407]
Subselects are a really powerful tool in SQL and PyDAL currently supports only a tiny fraction of their true power. I plan to fix that soon so I'm opening this thread for design discussion.

The obvious way to go is to make `db()._select()` return a table-like class instance that can then be executed as a "prepared statement" on its own or reused in other queries. It's also a necessary step for passing values properly through placeholders. The class will need to implement these methods:
- `__getitem__()` - only for accessing public fields by name; it won't do any DB queries
- `__call__()` - execute the prepared query and return any results
- `__setattr__()`
- `__iter__()`
- `__repr__()`
- `__str__()` - the query string (it'll raise exception if the query references external tables)
- `fields()` - public fields will be instances of FieldVirtual with the same name and type as the underlying query field/expression; nameless expressions will be excluded
- `as_dict()`
- `with_alias()`
- `on()`
- `_filter_fields()`
- another method that will internally generate the query string, with optional parameter for a list of external tables
- `ALL` - expands to the list of public fields

Some open questions:
- Should there be some public interface for accessing the query fields/expressions? (Meaning the field/expression arguments passed to `db()._select()`, in addition to their FieldVirtual representatives.)
- Should the list of public fields get populated only when `with_alias()` was called? (Subquery must always be aliased in a join.)
- Any suggestions for passing subqueries to `table.insert()`? The mapping between subquery result and destination table is done by position, not by name.

**Comment by gi0baro** [comment]
When I plan new features, I usually start thinking on the final syntax, so my missing point here is: what do you want to achieve?
Or, said in other words, how do you want the final users benefits from this feature? Can you give some examples of the final usage on this?

**Comment by nextghost** [comment]
Sure, I have a sanity check in my current project where I need to compare sums from two tables against a third table, like this:

    SELECT tab1.id, tab1.value + tmp1.sum - tmp2.sum AS diff FROM tab1
        LEFT JOIN (SELECT ref, SUM(value) AS sum FROM tab2 GROUP BY ref) AS tmp1 ON tab1.id = tmp1.ref
        LEFT JOIN (SELECT ref, SUM(value) AS sum FROM tab3 GROUP BY ref) AS tmp2 ON tab1.id = tmp2.ref
        WHERE tab1.value + tmp1.sum != tmp2.sum`

(The sum fields also need to be COALESCE()d but I've left that out for brevity.)

This is a single query that's blazing fast on the SQL server and returns only the rows that fail the check. But without full support for joinable subselects, I have to run those three `SELECT`s separately, iterate through the whole table in Python and check for mismatches myself. I know from experience that the execution time difference between those two methods can be hours vs. seconds.

**Comment by gi0baro** [comment]
@nextghost ok, but how would you write them in pydal? Can you post your idea for the final syntax on pyDAL for that query? Because I'm quite afraid the issue is not just on the subselects.

**Comment by nextghost** [comment]
Like this, obviously:

    sub1 = db()._select(db.tab2.ref, db.tab2.value.sum().with_alias('sum'), groupby=db.tab2.ref).with_alias('tmp1')
    sub2 = db()._select(db.tab3.ref, db.tab3.value.sum().with_alias('sum'), groupby=db.tab3.ref).with_alias('tmp2')
    diff = db.tab1.value + sub1.sum - sub2.sum
    left = [sub1.on(db.tab1.id == sub1.ref), sub2.on(db.tab1.id == sub2.ref)]
    result = db(db.tab1.value + sub1.sum != sub2.sum).select(db.tab1.id, diff.with_alias('diff'), left=left)

**Comment by nextghost** [comment]
Talk is cheap so I've pushed some code as pull request #408. We should continue there.
