### ISSUE TITLE
Wrong table/field names used in query construction

### ISSUE THREAD

**Issue by nextghost** [web2py/pydal#411]
While working on pull request #408, I've noticed that resolving the backend name of fields and tables is either brittle (lots and lots of duplicate code building the name from multiple object attributes) or already broken (`Table.sqlsafe` returns the correct backend name only when `Table._rname` is set or the table is not aliased, otherwise it'll return the alias which may either not exist in the database or refer to a completely different table).

I've introduced a new property `Table.real_name` in PR #408 that always returns the correct backend name of the table. However, fixing all instances of this problem is beyond the scope of that pull request so I'm reporting this here for later. `Field` doesn't have any property returning the correct full backend name/internal colname either because the `Field.sqlsafe` property relies on broken `Table.sqlsafe`. Whether to fix the existing properties or introduce new ones is open for debate.

**Comment by nextghost** [comment]
Small example:

    db.define_table('foo', Field('x'))
    db.foo.with_alias('bar').insert(x='xyz')

Result on PostgreSQL:

    ProgrammingError: relation "bar" does not exist
    LINE 1: INSERT INTO "bar"("x") VALUES ('xyz')RETURNING "id";
                        ^

**Comment by gi0baro** [comment]
@nextghost I don't agree to have another variable bound to the table for the naming. The current flow is already quite confusing.

Will inspect this carefully, and gonna propose a general change for naming and quoting (I already wanted to change the way tables and fields are quoted by pydal, 'cause it's a mess).

**Comment by nextghost** [comment]
Tables need 5 different table name properties because there are 5 different contexts:

1. Backend name without alias
2. Active backend alias (defaults to backend name)
3. Backend name *with* active backend alias (e.g. "rname AS alias")
4. Internal name under which the table is registered in DAL
5. Active internal alias (defaults to internal name)

The table object itself should provide all of these. The problem is that `Table.sqlsafe` is inconsistent and fits neither option which is the root cause of this bug. `Field` ends up needing 4 names:

1. Full backend name, including active backend table alias
2. Full internal name, including active internal table alias
3. Simple backend name
4. Simple internal name

All of these should be provided by the Table/Field object itself using the appropriate quoting methods. Building them outside the object (e.g. in the adapter) is asking for trouble.

**Comment by niphlod** [comment]
as long as the general idea of having rname be the uncluttered raw table name already quoted decoupled from the "nice" model name sticks, I'm good. 
I don't know if all of the above is needed (do I like to let the user choose the alias for the table? mmmhh, debatable) and/or wanted but I definitely feel pydal becoming more complicated than sqlalchemy. 
I know, confrontations with the top-dog are kinda unfair, but the level needed to dwelve in the pydal codebase is costantly raising. 
PS: every now and then a query reaches a certain level of complication that requires more and more to know beforehand what you want as a raw t-sql query and make pydal generate it rather the other way around (and the raw t-sql is shorter (characters and time wise) and clearer). I'd try to avoid wanting/coding features that reach that level of complexity because the only added benefit is for pydal to resolve the differences between backends (that at THAT kind of complication is rather "fixed", app's choice wise).

**Comment by nextghost** [comment]
@niphlod Whether you let the user choose the alias or generate it internally, you still need all of those names listed above over the lifetime of a *single SQL query* and associated with a specific `Table` instance, otherwise you can't do self-joins.

**Comment by nextghost** [comment]
Subselects are almost merged so here's my proposal how to fix this. As I've said [before](#issuecomment-244081622), tables need 5 different name attributes:

1. Backend name without alias
2. Active backend alias (defaults to backend name)
3. Backend name *with* active backend alias (e.g. "rname AS alias")
4. Internal name under which the table is registered in DAL
5. Active internal alias (defaults to internal name)

Those backend names should be provided by the following attributes:

1. `_rname` - unlike now, the attribute should default to quoted internal name (the name passed as first argument of `DAL.define_table()`)
2. `sqlsafe` - rewrite the currently broken logic
3. `sqlsafe_alias` - no change
4. `_dalname` - let's scrap the often missing `_ot` attribute and store the permanent internal name in a separate attribute that gets assigned by `__init__()`
5. `_tablename` - no change

Another alternative is to use `_tablename` as the permanent internal name and add `_alias` for the active alias (and initialize both with the same value). But this would require much more refactoring.

One small problem is that now it won't be possible to tell whether the table is aliased just by checking whether the `_ot` attribute exists. I recommend this new test: `table._tablename != table._dalname` (if true, table is aliased).

And now how to fix insert/update/delete for aliased tables: Fixing inserts is easy, field names are expanded without table alias so we can just use `_rname` in the query string instead of `sqlsafe`.

Updates and deletes are a bit tricky though. We can't just strip the alias for a moment because it'll break thread safety and it'll cause problems when support for joins in update/delete gets implemented in the future. But fortunately most SQL engines support aliasing the target table:

    UPDATE tablename AS alias SET ...
    DELETE FROM tablename AS alias WHERE ...

The only exception I've found so far is SQLite. So I recommend adding a new adapter method `writing_alias()` which will simply return `Table.sqlsafe_alias` and raise error where appropriate.

Any objections?

**Comment by gi0baro** [comment]
@nextghost ok here are my considerations:

- if you make `_rname` the quoted value, then why do you need `sqlsafe`? Probably I'm missing some pieces
- I was always quite afraid of *active* alias stored inside the table instance, because in a multi-threaded environment this can be a mess. Maybe we can take advantage of this refactoring to move this logic to contexts? (this is an idea, let's just talk about this)

**Comment by nextghost** [comment]
@gi0baro 
- `_rname` would be the unconditional real name of the table while `sqlsafe` is supposed to provide the (quoted) active alias. Those are not the same thing and we need both. But right now, accessing the real name of a table is ridiculously complicated.
- As long as the active alias never changes throughout the lifetime of a `Table` instance, it's fine. The new alias is always applied to a freshly created clone, remember? Also, I don't see any way to separate the active alias from the `Table` object. Could you be more specific about your idea?

**Comment by nextghost** [comment]
I've barely started refactoring and I'm already seeing `Table._tablename` used in places where it definitely doesn't belong. When I open the pull request for this, get ready for a flood of FIXMEs in places which I can't test myself.

**Comment by nextghost** [comment]
The pull request is now ready to be merged so I'm closing this.
