### ISSUE TITLE
error at py3

### ISSUE THREAD

**Issue by niphlod** [web2py/pydal#417]
imported from https://github.com/web2py/web2py/issues/1449

```diff
diff --git a/pydal/parsers/base.py b/pydal/parsers/base.py
index 2783fda..29944a7 100644
--- a/pydal/parsers/base.py
+++ b/pydal/parsers/base.py
@@ -34,7 +34,8 @@ class BasicParser(Parser):
 
     @for_type('blob')
     def _blob(self, value):
-        return to_native(b64decode(to_bytes(value)))
+        if PY2: return to_native(b64decode(to_bytes(value)))
+        else: return b64decode(value)
 
     @before_parse('reference')
     def reference_extras(self, field_type):
```

**Comment by gi0baro** [comment]
@niphlod I don't get why `to_native` which is both py2 and py3 compatible should be replaced with an if on `PY2` variable..

**Comment by niphlod** [comment]
neither do I. I'm just triaging.

**Comment by niphlod** [comment]
ok, I reviewed it and also think that is a wrong report (and a wrong fix, in the sense that nothing needs fixing in the first place).

@gi0baro , @ilvalle , @mdipierro , @RekGRpth : comments ?

**Comment by gi0baro** [comment]
@niphlod I gonna close it as invalid
