### ISSUE TITLE
validators?

### ISSUE THREAD

**Issue by rhr** [web2py/pydal#422]
Are validators out of scope for pydal? I tried to reuse a web2py model and it choked on the use of IS_NOT_EMPTY().

Thanks
-Rick

**Comment by mdipierro** [comment]
Can you tell us more in detail what you are doing?

**Comment by rhr** [comment]
I wanted to do some MySQL database record updates in a script. I had a web2py model for the database, but rather than do the updates through the web2py shell, I thought to try the standalone pydal. My model has some fields with `requires=IS_NOT_EMPTY()`, but I had do remove those validators for it to work in pydal. I was expecting to be able to just re-use web2py table definitions.

Thanks!

**Comment by gi0baro** [comment]
@rhr validators are in web2py and not included in pydal. To use web2py validators in pydal you should import them.

**Comment by gi0baro** [comment]
I'm gonna close this since is not pydal related.

**Comment by ZijianHe** [comment]
It is exactly pydal related as pydal could not be claimed as a library if there are no validators for its fields. There is no point to `pip install pydal` while I need to use web2py in the meanwhile

**Comment by gi0baro** [comment]
@ZijianHe there is no pydal validators. It's not the same layer of pydal and if you want to migrate from web2py then you have to migrate validators as well, since are in web2py. If you want a validation layer over pydal you have to implement it (eg: weppy has its own validators). pydal just have the interface to support validation.

**Comment by ZijianHe** [comment]
@gi0baro Thanks for the quick reply. I notice that there are validation related facilities in the code though there are no information on how to use them in a quick browsing. 

btw, the complete documentation listed at readme file is a little bit misguiding as it use the web2py docs with the use of gluon lib.

**Comment by gi0baro** [comment]
@ZijianHe yes you're right, nobody in the team had time to re-write all the docs just for the pydal layer. It's something that will come one day, hopefully :)

Regarding validators, pydal will accept any callable object. So you can write just a function:

```python
def will_accept_just_five(value):
    if value != 5:
        return value, "bad value"
    return value, None

db.table.field.requires = [will_accept_just_five]
```

or a class:

```python
class WillAcceptJustFive(object):
    def __call__(self, value):
        if value != 5:
            return value, "bad value"
        return value, None

db.table.field.requires = [WillAcceptJustFive()]
```

The important thing is that the callable object should accept the value to be validated as parameter and return a tuple in the form `(value, error)`.

**Comment by ZijianHe** [comment]
Thanks @gi0baro
