### ISSUE TITLE
Null fields with IS_DATETIME_IN_RANGE is validated

### ISSUE THREAD

**Issue by qtheuret** [web2py/pydal#423]
In my application, I have a field like this:
```
Field('download_date',
          type='datetime',
          required=False,
          notnull=False,
          requires=IS_DATETIME_IN_RANGE(maximum=request.now),
          label=T('Download date')),
```

This field is not required and can have a `null` value. But if my controller try to send data without value for this field (by using db.subscription.validate_and_insert function), I have the following error: `Row {'errors': {'download_date': 'Enter date and time on or before 2016-10-05 12:21:04'}, 'id': None}>`.
After checking the source code of `pydal`, I saw the https://github.com/web2py/pydal/commit/b57adea1f368fb1c9f299121f26cea557f1a5539 commit that change the behavior of the validators by checking all fields of the model instead of only sent fields.

I don't know if it's required to change the behavior of all validators to add a check for null value on each of them or change the call of validators to do not take care of `null` values.

**Comment by gi0baro** [comment]
@qtheuret just use web2py `IS_EMPTY_OR` validator which is intended to be used in these cases:

```python
Field('download_date', requires=IS_EMPTY_OR(IS_DATETIME_IN_RANGE(maximum=request.now)))
```

I'm closing this since is not pydal related.

**Comment by qtheuret** [comment]
Thanks for the answer.
