### ISSUE TITLE
Custom sqlite converter not handled correctly

### ISSUE THREAD

**Issue by maitscha** [web2py/pydal#437]
I'm using a custom sqlite3 converter in my app to return a time with timezone:

```python
try:
    import sqlite3

    # this is needed to convert a time bytestring from the database into
    # a Python time object including the tzinfo
    def convert_time(time):
        if time.endswith("+0"):
            time = time.replace("+0", "Z")
        return iso8601_to_time(time)

    sqlite3.register_converter(b"time", convert_time)
except:
    pass
```

This converter already returns a `datetime.time` object, so there's nothing which should be converted from pydal anymore. Problem is, that the `TimeParser` class only skips objects of type `datetime.datetime`, and thus tries to parse the value once more:

```python
class TimeParser(Parser):
    @for_type('time')
    def _time(self, value):
        if isinstance(value, datetime):
            return value.time()
        ... # parsing of time string
```

Actually this behaviour prevents me from switching to the pydal library. In older versions of the dal (the web2py integrated dal), the check was the other way round:

```python
def parse_time(self, value, field_type):
    if not isinstance(value, datetime.time):
        ... # parsing of time string
    return value
```

Or is it possible to override the `TimeParser` for the sqlite connector without forking the library?

**Comment by gi0baro** [comment]
You can customize the parser and register it over the sqlite adapter:

```python
from pydal.parsers import parsers, for_type
from pydal.parsers.sqlite import SQLiteParser
from pydal.adapters.sqlite import SQLite
@parsers.register_for(SQLite)
class CustomTimeParser(SQLiteParser):
    @for_type('time')
    def _time(self, value):
        return value
```

**Comment by maitscha** [comment]
Works great with the `CustomTimeParser`. Thanks for this great library, good job!
