### ISSUE TITLE
PostgreSQL connection parameters are not allowed by regex

### ISSUE THREAD

**Issue by maitscha** [web2py/pydal#438]
The PostgreSQL adapter uses a regex to validate the connection url:

https://github.com/web2py/pydal/blob/master/pydal/adapters/postgres.py#L33

This regex doesn't allow to use most of the PostgreSQL connection parameters:

https://www.postgresql.org/docs/9.0/static/libpq-connect.html

For example, `postgres://foo:bar@localhost:5432/foo?application_name=foo` would be a valid connection parameter.

Should we subclass and overwrite the `_initialize_` function of the `Postgre` adapter class, in order to set custom key/values in  `self.driver_args`?

**Comment by gi0baro** [comment]
@maitscha eventually you can change the parameters directly in the `connector`:

```python
from pydal.adapters import adapters
from pydal.adapters.postgres import Postgre

@adapters.register_for('postgres')
class CustomPostgre(Postgre)
    def connector(self):
        self.driver_args['db'] = 'myvalue'
        return self.driver.connect(**self.driver_args)
```

Or, if you end up with a regex rule that allow this, you can push a PR :)

**Comment by gi0baro** [comment]
@maitscha may I close this?

**Comment by maitscha** [comment]
Closed it, thank you for your help!
