### ISSUE TITLE
how to write the exists expression/query with pydal?

### ISSUE THREAD

**Issue by liuzhijun** [web2py/pydal#447]
SELECT * 
FROM cars AS T1 
WHERE 
    EXISTS 
    (
        SELECT * FROM Imperfections as T2 
        WHERE T1.uid = T2.uid AND imperfection = 1
    )
    AND EXISTS
    (
        SELECT * FROM Imperfections as T2 
        WHERE T1.uid = T2.uid AND imperfection = 2
    );
from: http://dba.stackexchange.com/questions/28431/many-to-one-subselection-in-single-query

I have tried this but it not perfect that the subquery should be write with dal:
from gluon.sql import SQLXorable as Expression, SQLQuery
db(Expression(db, "exists(select id FROM Imperfections WHERE T1.uid = T2.uid AND imperfection = 1)") & ...).select(...)

**Comment by Marlysson** [comment]
Why not `IN` in subquery or `JOIN` as sugested in thread in dba.exchange ? 

Pydal have `IN` and `JOIN` statement.

**Comment by liuzhijun** [comment]
IN is less effective then exists and JOIN will duplicate rows.

**Comment by niphlod** [comment]
IN has the exact same result. if your backend is less performant for IN vs EXISTS, either you

**Comment by nextghost** [comment]
As of PyDAL 17.01, you can do it like this:

    imp1 = db.imperfections.with_alias('imp1')
    imp2 = db.imperfections.with_alias('imp2')
    subq = ((imp1.uid == imp2.uid) & (imp1.imperfection == 1) & (imp2.imperfection == 2))
    sub = db(subq).nested_select(imp1.uid, distinct=True).with_alias('tmp')
    result = db(db.cars.uid == sub.uid).select(db.cars.ALL)
