### ISSUE TITLE
No method iterselect on sqlite backend

### ISSUE THREAD

**Issue by fpom** [web2py/pydal#454]
I'm trying to use `iterselect` with sqlite backend but I get:

```
AttributeError: 'Set' object has no attribute 'iterselect'
```

From the source code, I see it should inherit this method from parent class but it looks like it doesn't. Is it a bug or a feature?  ;)

Thanks for your help!
Franck

**Comment by BuhtigithuB** [comment]
Do you use web2py or pyDAL alone? Provide version of your build please as
iterselect is a recent addition and depending of the way you use pyDAL
(from web2py for example) you may not have the last version which may
explain the error you got. Also, you may consider showing the faultive
code...

On Tue, Mar 14, 2017 at 11:27 AM, Franck Pommereau <notifications@github.com

**Comment by fpom** [comment]
I use pyDAL alone. After updating to the latest version through pip, the problem has gone. My version was quite recent, I did not imagine it was such a new feature. Thanks!  :)
