### ISSUE TITLE
db(set) used inside requires=IS_IN_DB() make referenced table not lazy

### ISSUE THREAD

**Issue by BuhtigithuB** [web2py/pydal#455]
Is it possible to make set used inside IS_IN_DB() requires which are declared inside db.define_table not triggering model definition in context of lazy_tables = True??

Ref.: https://groups.google.com/d/msg/web2py/QGxZpM8vYy8/i2Hgfwb3AwAJ

Someone can use the attach app from the thread to reproduce the issue. Or just create a dummy app with at least 2 tables with one of them referencing the other and use a basic set like :

```python
IS_IN_DB(db(db.reference_table.id > 0), 'reference_table.id', '%(represent_field)s')
```

Instead of simply using : 

```python
IS_IN_DB(db, 'reference_table.id', '%(represent_field)s')
```

Then look at response.toolbar() db tables to see that in case set is used the "reference_table" is defined (not lazy).

**Comment by niphlod** [comment]
See the ondefine callback.

Il 15 mar 2017 5:18 PM, "BuhtigithuB" <notifications@github.com> ha scritto:

**Comment by BuhtigithuB** [comment]
I am reading

http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer?search=callback#on_define

Thanks

**Comment by BuhtigithuB** [comment]
Will do that...
It feels a bit hacky though.

I will close this ticket.

Thank you @niphlod

**Comment by niphlod** [comment]
It's not hacky
Its kind of parenthesis in math. Sometimes you just need them.

Il 15 mar 2017 5:59 PM, "BuhtigithuB" <notifications@github.com> ha scritto:

**Comment by abastardi** [comment]
> It feels a bit hacky though.

What do you propose as an alternative?

**Comment by BuhtigithuB** [comment]
Not much!

I will fix my app for now... I have a lot of work to do, but I am glad that I can keep all validators definition at the same place...

But I thought of something like using smart_query() instead of web2py set, so you could pass a string or a set... But I am don't know what could be the impact over the performance compare to on_define...
