### ISSUE TITLE
MySQL server has gone away while closing a connection in pool

### ISSUE THREAD

**Issue by gi0baro** [web2py/pydal#46]
https://github.com/web2py/web2py/issues/733

Seems quite dangerous.
I would like to know if this is about DAL or mysql adapter only.
@mdipierro Any ideas?

**Comment by mdipierro** [comment]
Nothing obvious comes to mind. Will investigate.

**Comment by ilvalle** [comment]
According to coveralls, that part is poorly tested.
https://coveralls.io/builds/1932476/source?filename=pydal%2Fconnection.py#L38

**Comment by gi0baro** [comment]
So, can we consider this completely fixed with https://github.com/web2py/pydal/pull/63?

**Comment by ilvalle** [comment]
I think so

**Comment by gi0baro** [comment]
OK, I'm closing this.
