### ISSUE TITLE
Migration fails when dropping a column on Postgresql

### ISSUE THREAD

**Issue by Doogli** [web2py/pydal#467]
Hi, running web2py version:
Version 2.14.6-stable+timestamp.2016.05.10.00.21.47
on ubuntu 16.04 with postgresql 9.6 and psycopg2

Below is a table definition, note the commented out field ('OS', rname='file_server_os') - I want to drop this column. 'audit' is just another table definition that I tag onto all my tables for updated_by, updated_on, etc 

db.define_table('FileServer',
            Field('HostName', rname='host_name', type='string', length=32, label='Host', comment='The Host Name of the Server on the network'),
            Field('Address', rname='file_server_address', type='string', length=32, label='Address', comment='The Address of the Server'),
            Field('CommissioningDate', rname='file_server_comm_date', type='date', label='Commissioning Date', comment='The date on which the Server was commissioned (YYYY-MM-DD)'),
            #Field('OS', rname='file_server_os', type='string', length=32, label='OS', comment='The Operating System running on the Server'),
            audit,
            rname='file_server',
            format='%(HostName)s',
            singular='Server',
            plural='Servers',
            migrate=True)

When I try to migrate this table, define_table fails with "relation fileserver does not exist" and in web2py's databases/sql.log:

timestamp: 2017-05-31T15:43:53.289791
ALTER TABLE FileServer DROP COLUMN os;

Seems the migration code does not support the new rname parameter for ALTER TABLE, which I find a good feature, especially for case agnostic DBs like postgres. It works fine for table creation, as this earlier entry in sql.log shows:

timestamp: 2017-05-30T13:10:09.134114
CREATE TABLE file_server(
    id SERIAL PRIMARY KEY,
    host_name VARCHAR(32),
    file_server_address VARCHAR(32),
    file_server_comm_date DATE,
    file_server_os VARCHAR(32),
    created_on TIMESTAMP,
    created_by INTEGER REFERENCES auth_user (id) ON DELETE CASCADE  ,
    updated_on TIMESTAMP,
    updated_by INTEGER REFERENCES auth_user (id) ON DELETE CASCADE  ,
    is_validated CHAR(1),
    is_active CHAR(1)
);
success!

I'm just gonna leave the offending field in there for now. Can somebody guesstimate the turnaround time on what seems a relatively simple bugfix like this?

Loving python and web2py for a painless start - currently in month 2 with both
\m/

**Comment by Doogli** [comment]
This is becoming a show-stopper for me now as I cannot ADD fields to an exiting table either. I'm pretty sure adding fields worked before when I was running on Windows. Made the transition to Linux on my office desktop recently and that was when I first encountered the problem. Adding the field LocalMountPoint (rname='storage_local_mount'):

self.db.define_table('StorageVolume',
            Field('VolumeName', rname='storage_volume_name', type='string', length=32, label='Volume', comment='The name of the Storage Volume'),
            Field('FileServerId', rname='storage_volume_server_id', type='reference FileServer', ondelete='CASCADE', label='Server', comment='The Server on which the Storage Volume resides'),
            Field('StorageUri', rname='storage_uri', type='string', length=256, label='Storage URI', comment='The URI of the Storage Volume'),
            Field('LocalMountPoint', rname='storage_local_mount', type='string', length=256, label='Local Mount Point', comment='The local mount point of the Storage Volume'),
            audit,
            rname='storage_volume',
            format='%(VolumeName)s',
            singular='Volume',
            plural='Volumes',
            migrate=True)
        self.db.commit()

results in:

ALTER TABLE storage_volume ADD localmountpoint VARCHAR(256);
success!

Aaaargh! Can anyone give feedback on how long this may take to fix? Can someone give me some pointers so I can fix it myself? As I said, bit of a noob to python and web2py... but how hard can it be? :)

**Comment by BuhtigithuB** [comment]
Read the code...

:-P

**Comment by mdipierro** [comment]
the problem seems to be that it tries to drop “os” instead of “file_server_os”. Which version of pydal are you using?

**Comment by BuhtigithuB** [comment]
Here the original thread on google groups :
https://groups.google.com/d/msg/web2py/Xzaglgu3pNU/_tRXLJj2AAAJ

**Comment by abastardi** [comment]
I think the problem is that the migration code doesn't use the field's `rname` when constructing the `DROP` and `ADD` statements. However, I think this is already fixed in the current master branch of PyDal -- see https://github.com/web2py/pydal/blob/881a533765bada3b1d63690f6549157f4e0508b9/pydal/migrator.py#L395. If someone can test master, we can close this issue.

**Comment by Doogli** [comment]
Sorry for the delayed response. I can confirm that the latest build from pydal does resolve the issue. I hear people speaking about the "trunk" in web2py, and although I understand this to mean the "latest stable" release, I'm not sure that the fix for this issue in pydal is included it the web2py "trunk". I may be wrong, but I don't have time to roll things back and see whether downloading and installing web2py again will fix it, or even to go and read the code. Thank you though for everyone's input and pointing me in the right direction. We can close the issue.

**Comment by mdipierro** [comment]
thanks for letting us know.
