### ISSUE TITLE
compute field ignored

### ISSUE THREAD

**Issue by dartg** [web2py/pydal#474]
The `compute` (not sure how this differs from `filter_in`, which is working by the way) field seems totally ignored:

```
>>> from pydal import DAL, Field
>>> def f(x): raise RuntimeError
...
>>> db = DAL("sqlite:memory:")
>>> db.define_table("mytable", Field("myfield", compute=f))
<Table mytable (id, myfield)>
>>> db.mytable.insert(myfield="Something")
1
```

The problem seems to be inside pydal/objects.py, in the function `Table._fields_and_values_for_insert`:

```
    def _fields_and_values_for_insert(self, fields):
        empty_fieldnames, new_fields = \
            self._filter_fields_for_operation(fields)
        to_compute = []
        for name in empty_fieldnames:
            field = self[name]
            if field.compute:
                to_compute.append((name, field))
            if field.default is not None:
                new_fields[name] = (field, field.default)
            elif field.required:
                raise RuntimeError(
                    'Table: missing required field: %s' % name)
        return self._compute_fields_for_operation(
            new_fields, to_compute)
```

`empty_fieldnames` is always `['id']`, so probably the bug is with `self._filter_fields_for_operation(fields)` which is returning bad information.

**Comment by gi0baro** [comment]
@dartg that's not the issue. The thing is pydal is silently catching exceptions in computed fields, so is not raising your error.

**Comment by dartg** [comment]
@gi0baro I don't think so. Try `def f(x): print(x)` and the function is never executed.

**Comment by gi0baro** [comment]
@dartg wait, I just realised you're using computed fields wrong. If you specify a value, then the computation doesn't occur. Computed fields are intended to be valued on other fields.

In the example you given pydal is just doing what you're saing. Inserting in the field the value you specified.

Please see http://web2py.com/books/default/chapter/29/06/the-database-abstraction-layer?search=computed#Computed-fields for more information.

**Comment by dartg** [comment]
@gi0baro My bad, you're right. Thanks.
