### ISSUE TITLE
uploadfs compatibility with pyfilesystem

### ISSUE THREAD

**Issue by xuyangbocn** [web2py/pydal#502]
Integrating uploadfs with pyfilesystem raise unicode error.
It seems pydal passes file path in python2 byte string, (refer to **Extract_1** below)
And pyfilesystem only accepts Unicode in python2. (refer to **Extract_2** below)

If uploadfs is only supporting pyfilesystem, pyDal could deal with the conversion internally before passing to pyfilesystem. Proposed change to Extract_2 from pyDal is below

            if self.uploadfs:
                dest_file = self.uploadfs.open(unicode(newfilename), 'wb')

**Extract_1** from https://github.com/web2py/pydal/blob/master/pydal/objects.py
Under class Field(Expression, Serializable), def store(self, file, filename=None, path=None)

        newfilename = '%s.%s.%s.%s' % (
            self._tablename, self.name, uuid_key, encoded_filename)
        newfilename = newfilename[:(self.length - 1 - len(extension))] + \
            '.' + extension
        self_uploadfield = self.uploadfield
        if isinstance(self_uploadfield, Field):
            blob_uploadfield_name = self_uploadfield.uploadfield
            keys = {self_uploadfield.name: newfilename,
                    blob_uploadfield_name: file.read()}
            self_uploadfield.table.insert(**keys)
        elif self_uploadfield is True:
            if self.uploadfs:
                dest_file = self.uploadfs.open(newfilename, 'wb')

**Extract_2** from https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/base.py
Under def validatepath(self, path):

        if isinstance(path, bytes):
            raise TypeError(
                'paths must be unicode (not str)'
                if six.PY2 else
                'paths must be str (not bytes)'
            )

**Comment by mdipierro** [comment]
This was fixed as recommended

**Comment by ybenitezf** [comment]
This is happening again but when you want to retrieve a file from the PyFilesystem

**Comment by ybenitezf** [comment]
```python
tbl = db.define_table('person', Field('my_foto', 'upload', uploadfs=PYFILESYS_INSTANCE, uploadseparate=True))
db.person.insert(my_foto=db.person.my_foto.store(stream, 'CHANGELOG'))
row = db().select(db.person.ALL)[0]
(filename, stream) = db.person.my_foto.retrieve(row.my_foto)
```
And u get the same error, it can be rounded by doing 

```python
(filename, stream) = db.person.my_foto.retrieve(unicode(row.my_foto))
```

**Comment by ybenitezf** [comment]
sorry, my bad, in pydal master branch is already fixed
