### ISSUE TITLE
unicodedecode exception reading back blob

### ISSUE THREAD

**Issue by simonm3** [web2py/pydal#583]
I try to insert a binary item into a blob field on sqlite. It appears to insert the record without error but when I read it back it raises a UnicodeDecodeError. Not sure why is is attempting to convert to unicode? I just want to get back the binary I put in. Is this a bug or if not then how do I insert binary data? The failed line is "to_native(b64decode(to_bytes(value)))" which appears to be a triple conversion.

Code is:

```
from db import db
db(db.task).delete()
db.commit()
task = b'\x80\x03'
db.task.insert(task=task)
db.commit()
db(db.task).select()
```

Exception is:

~\Anaconda3\lib\site-packages\pydal\parsers\__init__.py in _call(self, value, field_type)
     71 
     72     def _call(self, value, field_type):
---> 73         return self.f(self.parser, value)
     74 
     75     def __call__(self, value, field_type):

~\Anaconda3\lib\site-packages\pydal\parsers\base.py in _blob(self, value)
     35     @for_type('blob')
     36     def _blob(self, value):
---> 37         return to_native(b64decode(to_bytes(value)))
     38 
     39     @before_parse('reference')

~\Anaconda3\lib\site-packages\pydal\_compat.py in to_native(obj, charset, errors)
     80         if obj is None or isinstance(obj, str):
     81             return obj
---> 82         return obj.decode(charset, errors)
     83 
     84 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by mdipierro** [comment]
Tested with

```
import random
from pydal import DAL, Field
db =DAL()
db.define_table('x',
                Field('name'),
                Field('data', 'blob'))

db(db.x.id>0).delete()
random_data = b'\x80\x03'
print(repr(random_data[:100]))
id = db.x.insert(name="1", data=random_data)
row = db.x[id]
row.update_record(name="2")
assert row.data == random_data
```
and cannot reproduce.
