### ISSUE TITLE
Firebird Adaptor needs test_connection

### ISSUE THREAD

**Issue by villas** [web2py/pydal#611]
The base.py test_connection ('SELECT 1;') does not work for Firebird because a FROM clause is obligatory.   Therefore,  I suggest using a system table.  This works for me...

    def test_connection(self):
        self.execute('SELECT 1 FROM RDB$RELATION_FIELDS WHERE 1=0')

Please add this to pydal/adapters/firebird.py.  
Thanks.

**Comment by villas** [comment]
Could someone please add this function to:  pydal/adapters/firebird.py 
I have tried it with web2py and py4web and it works fine.
Many thanks!

**Comment by villas** [comment]
I think this sql string is slightly better using a single row table,  and 'first 0' guarantees that no rows are returned.

```
------------  pydal/adapters/firebird.py  ----------
def test_connection(self):
    self.execute('select first 0 1 from RDB$DATABASE')
```
BTW I have been waiting for over 2 months for this to be added.  What must I do to get this fixed?  Am I expected to make a pull request?  Does anyone review reported issues?

**Comment by valq7711** [comment]
Hi,  @villas 
I think if you make a PR + add this [proof](http://www.firebirdfaq.org/faq30) it will more than enouth for @mdipierro

**Comment by villas** [comment]
Hi @valq7711 I have made a pull request as you suggested

**Comment by villas** [comment]
Committed #628 today.  
https://github.com/web2py/pydal/commit/49d5457e0a036ef55cc5f5935ef82bf25db8d5d4
