### ISSUE TITLE
Why deleted the do_connect argument?

### ISSUE THREAD

**Issue by plter** [web2py/pydal#613]
pydal is a powerful and wonderful DAL lib, i use pydal in my project which based on asyncio lib, but pydal do not support asyncio, i use pydal to generate SQL string and then send it to aiomysql to execute, so the "do_connect" argument means much to me.

Could you put the argument back? or do you have any plan to support asyncio?

**Comment by timnyborg** [comment]
I think do_connect was removed because the DAL no longer automatically connects when first defined, as if do_connect is always False.  Instead it waits until you make an actual call.  So you can generate SQL strings without connecting to any database:

```
db = DAL("mysql://fake:db@fake:123/fake", migrate_enabled=False)
db.define_table('test', Field('id', 'id'))
db()._select(db.test.ALL)

Out: 'SELECT `test`.`id` FROM `test`;'
```

**Comment by plter** [comment]
Oh, i see, thank you very much.
