### ISSUE TITLE
Multiple URIs broken

### ISSUE THREAD

**Issue by timnyborg** [web2py/pydal#620]
Now that DAL connections only initialize on their first use, the DAL never tries the second URI in a list/tuple if the first fails.  Instead, it just errors out.

Presumably, this is because the error checking was done in the loop at:
https://github.com/web2py/pydal/blob/master/pydal/base.py#L485

For each URI, a connection was attempted.  But now, because no connection occurs there, no error can occur there to trigger an attempt on the next URI.  It assumes the first URI is fine, even if it isn't, and passes it to the adapter.

**Comment by Kkeller83** [comment]
I assume this will also affect py4web. Bummer, is there a workaround?

**Comment by timnyborg** [comment]
Yes, I've found a workaround, but it's ugly.  Using mssql as an example (others might not have executesql?):

Old:
```
dsn = ["mssql4n://...", "mssql4n://..."]
db = DAL(dsn)
```

New:
```
dsn = ["mssql4n://...", "mssql4n://..."]
principal, mirror = dsn
try:
    db = DAL(principal)
    idb.executesql('select 1')
except:
    db = DAL(mirror)
```

I'm loathe to implement this on a whole bunch of applications, so I'm hoping a real solution can be found.

**Comment by timnyborg** [comment]
Here's a better workaround in the pydal source:

In class DAL's def \_\_init\_\_, after
`self._adapter = adapter(**kwargs)`
I've added
```
if len(uris) > 1:
    self._adapter.connector()
```

This sort of negates the work @mdipierro did to delay the connection (though only for multiple uris), but it's working for me.
