### ISSUE TITLE
"Insert" return type for mongo

### ISSUE THREAD

**Issue by eevleevs** [web2py/pydal#625]
Hi, why does not "insert" return ObjectId instead than integer when working with mongo? In order to reuse the id in other queries, one needs to cast it back to ObjectId.

**Comment by mdipierro** [comment]
Legacy. There is to much logic in web2py that expects an int for id

**Comment by eevleevs** [comment]
Ok, for anyone else hitting `OverflowError: MongoDB can only handle up to 8-byte ints` when trying to reuse an id, here is what I did:

```
c1_id = db.c1.insert(**data)
db.c2.insert(c1_id=db._adapter.object_id(c1_id))
```
