### ISSUE TITLE
support for IN SQL statement

### ISSUE THREAD

**Issue by guruyaya** [web2py/pydal#659]
To be honest I was sure pydal has one. I cannot find it, so - i guess it's not in
I miss the option to use IN statement in queries. For example

    SELECT `table`.`name` FROM `table` WHERE `id` IN ('1', '2', '3')

I'd imaging the syntax going something like this:

    db(db.table.id.isin([1,2,3])).select(db.table.name)

**Comment by mdipierro** [comment]
The syntax is field.belongs([1,2,3])
