### ISSUE TITLE
Oracle adapter

### ISSUE THREAD

**Issue by Angy999** [web2py/pydal#666]
in the file oracle.py the code

    cmd_fix = re.compile("[^']*('[^']*'[^']*)*\:(?P<clob>(C|B)LOB\('([^']+|'')*'\))")

    def _initialize_(self, do_connect):
        super(Oracle, self)._initialize_(do_connect)
        ....

not work for me,  I believe it must be the following

    REGEX_CLOB = re.compile("[^']*('[^']*'[^']*)*\:(?P<clob>(C|B)LOB\('([^']+|'')*'\))")

    def _initialize_(self):
        super(Oracle, self)._initialize_()
        ....

thanks

**Comment by mdipierro** [comment]
I have no way of testing it but if the latter works for you I will change
it.

**Comment by Angy999** [comment]
OK Massimo, on web2py there is an error and it works with the change.
Comparing old versions I have that the init class has been rewritten 

Old class BaseAdapter

    def __init__(self, db, uri, pool_size=0, folder=None, db_codec='UTF-8',
                 credential_decoder=IDENTITY, driver_args={},
                 adapter_args={}, do_connect=True, after_connection=None,
                 entity_quoting=False):
        super(BaseAdapter, self).__init__()
        self._load_dependencies()
        self.db = db
        self.uri = uri
        self.pool_size = pool_size
        self.folder = folder
        self.db_codec = db_codec
        self.credential_decoder = credential_decoder
        self.driver_args = driver_args
        self.adapter_args = adapter_args
        self.expand = self._expand
        self._after_connection = after_connection
        self.connection = None
        self.find_driver()
        self._initialize_(do_connect)
        if do_connect:
            self.reconnect()


New class BaseAdapter :

    def __init__(
        self,
        db,
        uri,
        pool_size=0,
        folder=None,
        db_codec="UTF-8",
        credential_decoder=IDENTITY,
        driver_args={},
        adapter_args={},
        after_connection=None,
        entity_quoting=False
    ):
        super(BaseAdapter, self).__init__()
        self._load_dependencies()
        self.db = db
        self.uri = uri
        self.pool_size = pool_size
        self.folder = folder
        self.db_codec = db_codec
        self.credential_decoder = credential_decoder
        self.driver_args = driver_args
        self.adapter_args = adapter_args
        self.expand = self._expand
        self._after_connection = after_connection
        self.set_connection(None)
        self.find_driver()
        self._initialize_()



And now for example I no longer see the option "do_connect = True"

Then in line 51 of the oracle.py file there is the line "
m = re.match (self.REGEX_CLOB, command) "

but it is not defined" self.REGEX_CLOB ",

 it should be cmd_fix which I renamed.

However now it works for me and connects to an Oracle Rac 12.0.2

I hope to be proved helpful

**Comment by mdipierro** [comment]
Thanks you. This helps a lot. Will fix it as you suggested.

**Comment by Angy999** [comment]
Thanks
