### ISSUE TITLE
The user name or password contains @, unable to connect to MySQL

### ISSUE THREAD

**Issue by navysummer** [web2py/pydal#676]
The user name or password contains @, unable to connect to MySQL

**Comment by navysummer** [comment]
Recommended connection mode support parameters:DAL(host="",port="",user="",password="",db="",**kwargs)

**Comment by navysummer** [comment]
Recommended modify the regular

**Comment by niphlod** [comment]
there's no need, you need to use decode_credentials=True and quote them

**Comment by mdipierro** [comment]
Closing because of niphlod solution.
