### ISSUE TITLE
problem with .contains() when passing list as argument

### ISSUE THREAD

**Issue by unle70** [web2py/pydal#685]
I was trying to use .contains() and compared 2 cases:

a. Passing a DAL field (db.table.column) as parameter to the .contains()
b. Passing a list where one item is a DAL field ( ['a', 'b', db.table.column] ) to the .contains()

In case 'a' everything works as expected.
In case 'b' the column name is set in the SQL to be just a string (quoted) and not working properly.

I hope what I'm trying to do in 'b' above can be made to work.

Thanks,
Udi

**Comment by mdipierro** [comment]
The proper use of contains is db.table.field.contains(value) a value should be a string a number (for list of integers) or a string. I am amazed and happy that it works when the value is another field, although that may not be supported by all database engines. Passing a list is not supported but you can do:

OR = lambda a,b: a|b
query = reduce(OR, map(db.table.column.contains, ['a', 'b', 'c']))
