### ISSUE TITLE
erro calling db.uuid method

### ISSUE THREAD

**Issue by manuelep** [web2py/pydal#689]
https://github.com/web2py/pydal/blame/v20220609.1/pydal/base.py#L298

db.uuid method is called (as it's normal for a class method) with self as first argument but it correspond to a function that accepts no parameter, so it always raises an exception 

at least line [298](https://github.com/web2py/pydal/blob/v20220213.2/pydal/base.py#L298) in base.py should be substituted with:

```py
uuid = lambda self:  uuidstr()
```

**Comment by mdipierro** [comment]
fixed
