### ISSUE TITLE
count field in restapi

### ISSUE THREAD

**Issue by vincentchevrier** [web2py/pydal#690]
Using the py4web documentation [example ](https://py4web.com/_documentation/static/en/chapter-08.html) of pydal.restapi.

The following url
`http://127.0.0.1:8000/superheroes/api/tag?@limit=1&@count=True`
will give the following response
```
{
  "api_version": "0.1",
  "code": 200,
  "count": 10,
  "items": [
    {
      "id": 1,
      "strength": 100,
      "superhero": 1,
      "superpower": 1
    }
  ],
  "status": "success",
  "timestamp": "2022-07-06T21:09:10.940419"
}
```

note that the `count` is incorrect, as it should be `1`.
I believe this is because the rows are filtered by `limit` after applying the `query` here:
https://github.com/web2py/pydal/blob/daa85d447ebe4ed9d4777f56b773f7f416e2a544/pydal/restapi.py#L464-L466

but count is obtained using only the `query` which does not apply the `limit`
https://github.com/web2py/pydal/blob/daa85d447ebe4ed9d4777f56b773f7f416e2a544/pydal/restapi.py#L584

Presumably `count` could be obtained by using the length of `rows` instead?

**Comment by mdipierro** [comment]
It is not incorrect. count is not supposed to return the number of items in the current response but the total number number of items matching the query. So you know if you need to query for more or not.
