### ISSUE TITLE
pyDAL 20240427 breaks web2py (master)

### ISSUE THREAD

**Issue by fambon** [web2py/pydal#715]
see https://github.com/web2py/web2py/issues/2486

```
  File "/home/pci/pci/web2py/gluon/tools.py", line 3273, in login
    user = Row(table_user._filter_fields(user, id=True))
TypeError: _filter_fields() got an unexpected keyword argument 'id'
```

https://github.com/web2py/web2py/blob/master/gluon/tools.py#L3273

**Comment by fambon** [comment]
maybe it's more etiquette to re-add kw arg `id` on `_filter_fields()` for backward compatibility?

**Comment by mdipierro** [comment]
will fix it in web2py
