### ISSUE TITLE
Python 3.13 incompatibility: missing 'cgi' module 

### ISSUE THREAD

**Issue by nicozanf** [web2py/pydal#718]
after being deprecated, the 'cgi' module has been totally removed from python 3.13.0 - where now the current pyDAL cannot run. This is also blocking  python 3.13 compatibility of py4web. The same problems has just been fixed with ombott 2.3.

I's used on pydal/objects.py , pydal/validators.py and tests/validators.py

**Comment by mdipierro** [comment]
Fix merged - please check everything works as expecte.
