### ISSUE TITLE
mongo db warning

### ISSUE THREAD

**Issue by ilvalle** [web2py/pydal#79]
On travis-ci I noticied the following:
```
pydal/adapters/mongo.py:365: DeprecationWarning: The safe parameter is deprecated. Please use write concern options instead.
  ctable.insert(values, safe=safe)
```

**Comment by gi0baro** [comment]
@ilvalle I'm closing this since @mdipierro merged https://github.com/web2py/pydal/pull/102
Feel free to re-open if you don't like the solution or want to make changes.
