### ISSUE TITLE
Duplicated signatures in mongo adapter

### ISSUE THREAD

**Issue by ilvalle** [web2py/pydal#88]
The methods **LIKE**, **STARTSWITH**, **ENDSWITH**, **CONTAINS** are defined twice.
For each of them, which is the one to delete and the one to use?

**Comment by niphlod** [comment]
I see that first occurrences handle more cases than the last. Dropping the last (and verifying that tests pass) should be the easy way to verify that,

**Comment by ilvalle** [comment]
I'll verify because it should be the last occurrence the one used

**Comment by ilvalle** [comment]
Actually, there are no tests that covers such methods https://coveralls.io/builds/2122836/source?filename=pydal%2Fadapters%2Fmongo.py

**Comment by stephenrauch** [comment]
@ilvalle, did the recent work on **LIKE** and **CONTAINS** resolve this bug?

**Comment by ilvalle** [comment]
yes of course.
