### ISSUE TITLE
nosql not operator

### ISSUE THREAD

**Issue by ilvalle** [web2py/pydal#97]
On gae the ```not``` operator is not implemented; on mongodb it doesn't work for expression such as ```~(db.tt.aa > 2)``` (it throws *cmd failed: unknown top level operator: $not*).
However, under some constraints it should be feasible to convert the expression into  ```(db.tt.aa <= 2)``` for both engines. Can De Morgan law help us in such situation? Do you see any drawback?

**Comment by mdipierro** [comment]
I agree. we should be able to do it.

**Comment by ilvalle** [comment]
I created a PR for mongo db.
GAE is feasible but it is different because it requires to invert the operator at pydal level.
